// This file was automatically generated by ctpgen
#ifndef GEN_MD_API_H
#define GEN_MD_API_H
#include <stdint.h>
#include "gen_types.h"
#ifdef  __cplusplus
extern "C"{
#endif

typedef void* mdApi;
typedef void* mdSpi;

mdSpi md_new_spi(uint64_t value);


mdApi md_create_ftdc_md_api(char * pszFlowPath,int8_t bIsUsingUdp,int8_t bIsMulticast);
const char * md_get_api_version();

void md_release(mdApi a);
void md_init(mdApi a);
int md_join(mdApi a);
const char * md_get_trading_day(mdApi a);
void md_register_front(mdApi a, char * pszFrontAddress);
void md_register_name_server(mdApi a, char * pszNsAddress);
void md_register_fens_user_info(mdApi a, CThostFtdcFensUserInfoField * pFensUserInfo);
void md_register_spi(mdApi a, mdSpi s);
int md_subscribe_market_data(mdApi a, char* ppInstrumentID[], int nCount);
int md_un_subscribe_market_data(mdApi a, char* ppInstrumentID[], int nCount);
int md_subscribe_for_quote_rsp(mdApi a, char* ppInstrumentID[], int nCount);
int md_un_subscribe_for_quote_rsp(mdApi a, char* ppInstrumentID[], int nCount);
int md_req_user_login(mdApi a, CThostFtdcReqUserLoginField * pReqUserLoginField, int nRequestID);
int md_req_user_logout(mdApi a, CThostFtdcUserLogoutField * pUserLogout, int nRequestID);
int md_req_qry_multicast_instrument(mdApi a, CThostFtdcQryMulticastInstrumentField * pQryMulticastInstrument, int nRequestID);

#ifdef  __cplusplus
};
#endif
#endif  // GEN_MD_API_H