// This file was automatically generated by ctpgen
#include "gen_td_api.h"
#include "include/ThostFtdcTraderApi.h"
#include "gen_td_spi.h"

tdSpi td_new_spi(uint64_t value){
  CThostFtdcTraderSpiImpl *p = new CThostFtdcTraderSpiImpl(value);
  return tdSpi(p);
}

void td_spi_free(tdSpi p){
  CThostFtdcTraderSpiImpl *ptr = (CThostFtdcTraderSpiImpl *)p;
  delete ptr;
}



tdApi td_create_ftdc_trader_api(char * pszFlowPath){
  CThostFtdcTraderApi* p = CThostFtdcTraderApi::CreateFtdcTraderApi(pszFlowPath);
  return (tdApi)p;
}
const char * td_get_api_version(){
  return CThostFtdcTraderApi::GetApiVersion();
}


void td_release(tdApi a){
  CThostFtdcTraderApi* p = (CThostFtdcTraderApi*)a;
  p->Release();
}
void td_init(tdApi a){
  CThostFtdcTraderApi* p = (CThostFtdcTraderApi*)a;
  p->Init();
}
int td_join(tdApi a){
  CThostFtdcTraderApi* p = (CThostFtdcTraderApi*)a;
  return p->Join();
}
const char * td_get_trading_day(tdApi a){
  CThostFtdcTraderApi* p = (CThostFtdcTraderApi*)a;
  return p->GetTradingDay();
}
void td_register_front(tdApi a, char * pszFrontAddress){
  CThostFtdcTraderApi* p = (CThostFtdcTraderApi*)a;
  p->RegisterFront(pszFrontAddress);
}
void td_register_name_server(tdApi a, char * pszNsAddress){
  CThostFtdcTraderApi* p = (CThostFtdcTraderApi*)a;
  p->RegisterNameServer(pszNsAddress);
}
void td_register_fens_user_info(tdApi a, CThostFtdcFensUserInfoField * pFensUserInfo){
  CThostFtdcTraderApi* p = (CThostFtdcTraderApi*)a;
  p->RegisterFensUserInfo(pFensUserInfo);
}
void td_register_spi(tdApi a, tdSpi s){
  CThostFtdcTraderApi* p = (CThostFtdcTraderApi*)a;
  CThostFtdcTraderSpi* spi = (CThostFtdcTraderSpi*)s;
  p->RegisterSpi(spi);
}
void td_subscribe_private_topic(tdApi a, THOST_TE_RESUME_TYPE nResumeType){
  CThostFtdcTraderApi* p = (CThostFtdcTraderApi*)a;
  p->SubscribePrivateTopic(nResumeType);
}
void td_subscribe_public_topic(tdApi a, THOST_TE_RESUME_TYPE nResumeType){
  CThostFtdcTraderApi* p = (CThostFtdcTraderApi*)a;
  p->SubscribePublicTopic(nResumeType);
}
int td_req_authenticate(tdApi a, CThostFtdcReqAuthenticateField * pReqAuthenticateField, int nRequestID){
  CThostFtdcTraderApi* p = (CThostFtdcTraderApi*)a;
  return p->ReqAuthenticate(pReqAuthenticateField,nRequestID);
}
int td_register_user_system_info(tdApi a, CThostFtdcUserSystemInfoField * pUserSystemInfo){
  CThostFtdcTraderApi* p = (CThostFtdcTraderApi*)a;
  return p->RegisterUserSystemInfo(pUserSystemInfo);
}
int td_submit_user_system_info(tdApi a, CThostFtdcUserSystemInfoField * pUserSystemInfo){
  CThostFtdcTraderApi* p = (CThostFtdcTraderApi*)a;
  return p->SubmitUserSystemInfo(pUserSystemInfo);
}
int td_req_user_login(tdApi a, CThostFtdcReqUserLoginField * pReqUserLoginField, int nRequestID){
  CThostFtdcTraderApi* p = (CThostFtdcTraderApi*)a;
  return p->ReqUserLogin(pReqUserLoginField,nRequestID);
}
int td_req_user_logout(tdApi a, CThostFtdcUserLogoutField * pUserLogout, int nRequestID){
  CThostFtdcTraderApi* p = (CThostFtdcTraderApi*)a;
  return p->ReqUserLogout(pUserLogout,nRequestID);
}
int td_req_user_password_update(tdApi a, CThostFtdcUserPasswordUpdateField * pUserPasswordUpdate, int nRequestID){
  CThostFtdcTraderApi* p = (CThostFtdcTraderApi*)a;
  return p->ReqUserPasswordUpdate(pUserPasswordUpdate,nRequestID);
}
int td_req_trading_account_password_update(tdApi a, CThostFtdcTradingAccountPasswordUpdateField * pTradingAccountPasswordUpdate, int nRequestID){
  CThostFtdcTraderApi* p = (CThostFtdcTraderApi*)a;
  return p->ReqTradingAccountPasswordUpdate(pTradingAccountPasswordUpdate,nRequestID);
}
int td_req_user_auth_method(tdApi a, CThostFtdcReqUserAuthMethodField * pReqUserAuthMethod, int nRequestID){
  CThostFtdcTraderApi* p = (CThostFtdcTraderApi*)a;
  return p->ReqUserAuthMethod(pReqUserAuthMethod,nRequestID);
}
int td_req_gen_user_captcha(tdApi a, CThostFtdcReqGenUserCaptchaField * pReqGenUserCaptcha, int nRequestID){
  CThostFtdcTraderApi* p = (CThostFtdcTraderApi*)a;
  return p->ReqGenUserCaptcha(pReqGenUserCaptcha,nRequestID);
}
int td_req_gen_user_text(tdApi a, CThostFtdcReqGenUserTextField * pReqGenUserText, int nRequestID){
  CThostFtdcTraderApi* p = (CThostFtdcTraderApi*)a;
  return p->ReqGenUserText(pReqGenUserText,nRequestID);
}
int td_req_user_login_with_captcha(tdApi a, CThostFtdcReqUserLoginWithCaptchaField * pReqUserLoginWithCaptcha, int nRequestID){
  CThostFtdcTraderApi* p = (CThostFtdcTraderApi*)a;
  return p->ReqUserLoginWithCaptcha(pReqUserLoginWithCaptcha,nRequestID);
}
int td_req_user_login_with_text(tdApi a, CThostFtdcReqUserLoginWithTextField * pReqUserLoginWithText, int nRequestID){
  CThostFtdcTraderApi* p = (CThostFtdcTraderApi*)a;
  return p->ReqUserLoginWithText(pReqUserLoginWithText,nRequestID);
}
int td_req_user_login_with_o_t_p(tdApi a, CThostFtdcReqUserLoginWithOTPField * pReqUserLoginWithOTP, int nRequestID){
  CThostFtdcTraderApi* p = (CThostFtdcTraderApi*)a;
  return p->ReqUserLoginWithOTP(pReqUserLoginWithOTP,nRequestID);
}
int td_req_order_insert(tdApi a, CThostFtdcInputOrderField * pInputOrder, int nRequestID){
  CThostFtdcTraderApi* p = (CThostFtdcTraderApi*)a;
  return p->ReqOrderInsert(pInputOrder,nRequestID);
}
int td_req_parked_order_insert(tdApi a, CThostFtdcParkedOrderField * pParkedOrder, int nRequestID){
  CThostFtdcTraderApi* p = (CThostFtdcTraderApi*)a;
  return p->ReqParkedOrderInsert(pParkedOrder,nRequestID);
}
int td_req_parked_order_action(tdApi a, CThostFtdcParkedOrderActionField * pParkedOrderAction, int nRequestID){
  CThostFtdcTraderApi* p = (CThostFtdcTraderApi*)a;
  return p->ReqParkedOrderAction(pParkedOrderAction,nRequestID);
}
int td_req_order_action(tdApi a, CThostFtdcInputOrderActionField * pInputOrderAction, int nRequestID){
  CThostFtdcTraderApi* p = (CThostFtdcTraderApi*)a;
  return p->ReqOrderAction(pInputOrderAction,nRequestID);
}
int td_req_query_max_order_volume(tdApi a, CThostFtdcQueryMaxOrderVolumeField * pQueryMaxOrderVolume, int nRequestID){
  CThostFtdcTraderApi* p = (CThostFtdcTraderApi*)a;
  return p->ReqQueryMaxOrderVolume(pQueryMaxOrderVolume,nRequestID);
}
int td_req_settlement_info_confirm(tdApi a, CThostFtdcSettlementInfoConfirmField * pSettlementInfoConfirm, int nRequestID){
  CThostFtdcTraderApi* p = (CThostFtdcTraderApi*)a;
  return p->ReqSettlementInfoConfirm(pSettlementInfoConfirm,nRequestID);
}
int td_req_remove_parked_order(tdApi a, CThostFtdcRemoveParkedOrderField * pRemoveParkedOrder, int nRequestID){
  CThostFtdcTraderApi* p = (CThostFtdcTraderApi*)a;
  return p->ReqRemoveParkedOrder(pRemoveParkedOrder,nRequestID);
}
int td_req_remove_parked_order_action(tdApi a, CThostFtdcRemoveParkedOrderActionField * pRemoveParkedOrderAction, int nRequestID){
  CThostFtdcTraderApi* p = (CThostFtdcTraderApi*)a;
  return p->ReqRemoveParkedOrderAction(pRemoveParkedOrderAction,nRequestID);
}
int td_req_exec_order_insert(tdApi a, CThostFtdcInputExecOrderField * pInputExecOrder, int nRequestID){
  CThostFtdcTraderApi* p = (CThostFtdcTraderApi*)a;
  return p->ReqExecOrderInsert(pInputExecOrder,nRequestID);
}
int td_req_exec_order_action(tdApi a, CThostFtdcInputExecOrderActionField * pInputExecOrderAction, int nRequestID){
  CThostFtdcTraderApi* p = (CThostFtdcTraderApi*)a;
  return p->ReqExecOrderAction(pInputExecOrderAction,nRequestID);
}
int td_req_for_quote_insert(tdApi a, CThostFtdcInputForQuoteField * pInputForQuote, int nRequestID){
  CThostFtdcTraderApi* p = (CThostFtdcTraderApi*)a;
  return p->ReqForQuoteInsert(pInputForQuote,nRequestID);
}
int td_req_quote_insert(tdApi a, CThostFtdcInputQuoteField * pInputQuote, int nRequestID){
  CThostFtdcTraderApi* p = (CThostFtdcTraderApi*)a;
  return p->ReqQuoteInsert(pInputQuote,nRequestID);
}
int td_req_quote_action(tdApi a, CThostFtdcInputQuoteActionField * pInputQuoteAction, int nRequestID){
  CThostFtdcTraderApi* p = (CThostFtdcTraderApi*)a;
  return p->ReqQuoteAction(pInputQuoteAction,nRequestID);
}
int td_req_batch_order_action(tdApi a, CThostFtdcInputBatchOrderActionField * pInputBatchOrderAction, int nRequestID){
  CThostFtdcTraderApi* p = (CThostFtdcTraderApi*)a;
  return p->ReqBatchOrderAction(pInputBatchOrderAction,nRequestID);
}
int td_req_option_self_close_insert(tdApi a, CThostFtdcInputOptionSelfCloseField * pInputOptionSelfClose, int nRequestID){
  CThostFtdcTraderApi* p = (CThostFtdcTraderApi*)a;
  return p->ReqOptionSelfCloseInsert(pInputOptionSelfClose,nRequestID);
}
int td_req_option_self_close_action(tdApi a, CThostFtdcInputOptionSelfCloseActionField * pInputOptionSelfCloseAction, int nRequestID){
  CThostFtdcTraderApi* p = (CThostFtdcTraderApi*)a;
  return p->ReqOptionSelfCloseAction(pInputOptionSelfCloseAction,nRequestID);
}
int td_req_comb_action_insert(tdApi a, CThostFtdcInputCombActionField * pInputCombAction, int nRequestID){
  CThostFtdcTraderApi* p = (CThostFtdcTraderApi*)a;
  return p->ReqCombActionInsert(pInputCombAction,nRequestID);
}
int td_req_qry_order(tdApi a, CThostFtdcQryOrderField * pQryOrder, int nRequestID){
  CThostFtdcTraderApi* p = (CThostFtdcTraderApi*)a;
  return p->ReqQryOrder(pQryOrder,nRequestID);
}
int td_req_qry_trade(tdApi a, CThostFtdcQryTradeField * pQryTrade, int nRequestID){
  CThostFtdcTraderApi* p = (CThostFtdcTraderApi*)a;
  return p->ReqQryTrade(pQryTrade,nRequestID);
}
int td_req_qry_investor_position(tdApi a, CThostFtdcQryInvestorPositionField * pQryInvestorPosition, int nRequestID){
  CThostFtdcTraderApi* p = (CThostFtdcTraderApi*)a;
  return p->ReqQryInvestorPosition(pQryInvestorPosition,nRequestID);
}
int td_req_qry_trading_account(tdApi a, CThostFtdcQryTradingAccountField * pQryTradingAccount, int nRequestID){
  CThostFtdcTraderApi* p = (CThostFtdcTraderApi*)a;
  return p->ReqQryTradingAccount(pQryTradingAccount,nRequestID);
}
int td_req_qry_investor(tdApi a, CThostFtdcQryInvestorField * pQryInvestor, int nRequestID){
  CThostFtdcTraderApi* p = (CThostFtdcTraderApi*)a;
  return p->ReqQryInvestor(pQryInvestor,nRequestID);
}
int td_req_qry_trading_code(tdApi a, CThostFtdcQryTradingCodeField * pQryTradingCode, int nRequestID){
  CThostFtdcTraderApi* p = (CThostFtdcTraderApi*)a;
  return p->ReqQryTradingCode(pQryTradingCode,nRequestID);
}
int td_req_qry_instrument_margin_rate(tdApi a, CThostFtdcQryInstrumentMarginRateField * pQryInstrumentMarginRate, int nRequestID){
  CThostFtdcTraderApi* p = (CThostFtdcTraderApi*)a;
  return p->ReqQryInstrumentMarginRate(pQryInstrumentMarginRate,nRequestID);
}
int td_req_qry_instrument_commission_rate(tdApi a, CThostFtdcQryInstrumentCommissionRateField * pQryInstrumentCommissionRate, int nRequestID){
  CThostFtdcTraderApi* p = (CThostFtdcTraderApi*)a;
  return p->ReqQryInstrumentCommissionRate(pQryInstrumentCommissionRate,nRequestID);
}
int td_req_qry_exchange(tdApi a, CThostFtdcQryExchangeField * pQryExchange, int nRequestID){
  CThostFtdcTraderApi* p = (CThostFtdcTraderApi*)a;
  return p->ReqQryExchange(pQryExchange,nRequestID);
}
int td_req_qry_product(tdApi a, CThostFtdcQryProductField * pQryProduct, int nRequestID){
  CThostFtdcTraderApi* p = (CThostFtdcTraderApi*)a;
  return p->ReqQryProduct(pQryProduct,nRequestID);
}
int td_req_qry_instrument(tdApi a, CThostFtdcQryInstrumentField * pQryInstrument, int nRequestID){
  CThostFtdcTraderApi* p = (CThostFtdcTraderApi*)a;
  return p->ReqQryInstrument(pQryInstrument,nRequestID);
}
int td_req_qry_depth_market_data(tdApi a, CThostFtdcQryDepthMarketDataField * pQryDepthMarketData, int nRequestID){
  CThostFtdcTraderApi* p = (CThostFtdcTraderApi*)a;
  return p->ReqQryDepthMarketData(pQryDepthMarketData,nRequestID);
}
int td_req_qry_settlement_info(tdApi a, CThostFtdcQrySettlementInfoField * pQrySettlementInfo, int nRequestID){
  CThostFtdcTraderApi* p = (CThostFtdcTraderApi*)a;
  return p->ReqQrySettlementInfo(pQrySettlementInfo,nRequestID);
}
int td_req_qry_transfer_bank(tdApi a, CThostFtdcQryTransferBankField * pQryTransferBank, int nRequestID){
  CThostFtdcTraderApi* p = (CThostFtdcTraderApi*)a;
  return p->ReqQryTransferBank(pQryTransferBank,nRequestID);
}
int td_req_qry_investor_position_detail(tdApi a, CThostFtdcQryInvestorPositionDetailField * pQryInvestorPositionDetail, int nRequestID){
  CThostFtdcTraderApi* p = (CThostFtdcTraderApi*)a;
  return p->ReqQryInvestorPositionDetail(pQryInvestorPositionDetail,nRequestID);
}
int td_req_qry_notice(tdApi a, CThostFtdcQryNoticeField * pQryNotice, int nRequestID){
  CThostFtdcTraderApi* p = (CThostFtdcTraderApi*)a;
  return p->ReqQryNotice(pQryNotice,nRequestID);
}
int td_req_qry_settlement_info_confirm(tdApi a, CThostFtdcQrySettlementInfoConfirmField * pQrySettlementInfoConfirm, int nRequestID){
  CThostFtdcTraderApi* p = (CThostFtdcTraderApi*)a;
  return p->ReqQrySettlementInfoConfirm(pQrySettlementInfoConfirm,nRequestID);
}
int td_req_qry_investor_position_combine_detail(tdApi a, CThostFtdcQryInvestorPositionCombineDetailField * pQryInvestorPositionCombineDetail, int nRequestID){
  CThostFtdcTraderApi* p = (CThostFtdcTraderApi*)a;
  return p->ReqQryInvestorPositionCombineDetail(pQryInvestorPositionCombineDetail,nRequestID);
}
int td_req_qry_c_f_m_m_c_trading_account_key(tdApi a, CThostFtdcQryCFMMCTradingAccountKeyField * pQryCFMMCTradingAccountKey, int nRequestID){
  CThostFtdcTraderApi* p = (CThostFtdcTraderApi*)a;
  return p->ReqQryCFMMCTradingAccountKey(pQryCFMMCTradingAccountKey,nRequestID);
}
int td_req_qry_e_warrant_offset(tdApi a, CThostFtdcQryEWarrantOffsetField * pQryEWarrantOffset, int nRequestID){
  CThostFtdcTraderApi* p = (CThostFtdcTraderApi*)a;
  return p->ReqQryEWarrantOffset(pQryEWarrantOffset,nRequestID);
}
int td_req_qry_investor_product_group_margin(tdApi a, CThostFtdcQryInvestorProductGroupMarginField * pQryInvestorProductGroupMargin, int nRequestID){
  CThostFtdcTraderApi* p = (CThostFtdcTraderApi*)a;
  return p->ReqQryInvestorProductGroupMargin(pQryInvestorProductGroupMargin,nRequestID);
}
int td_req_qry_exchange_margin_rate(tdApi a, CThostFtdcQryExchangeMarginRateField * pQryExchangeMarginRate, int nRequestID){
  CThostFtdcTraderApi* p = (CThostFtdcTraderApi*)a;
  return p->ReqQryExchangeMarginRate(pQryExchangeMarginRate,nRequestID);
}
int td_req_qry_exchange_margin_rate_adjust(tdApi a, CThostFtdcQryExchangeMarginRateAdjustField * pQryExchangeMarginRateAdjust, int nRequestID){
  CThostFtdcTraderApi* p = (CThostFtdcTraderApi*)a;
  return p->ReqQryExchangeMarginRateAdjust(pQryExchangeMarginRateAdjust,nRequestID);
}
int td_req_qry_exchange_rate(tdApi a, CThostFtdcQryExchangeRateField * pQryExchangeRate, int nRequestID){
  CThostFtdcTraderApi* p = (CThostFtdcTraderApi*)a;
  return p->ReqQryExchangeRate(pQryExchangeRate,nRequestID);
}
int td_req_qry_sec_agent_a_c_i_d_map(tdApi a, CThostFtdcQrySecAgentACIDMapField * pQrySecAgentACIDMap, int nRequestID){
  CThostFtdcTraderApi* p = (CThostFtdcTraderApi*)a;
  return p->ReqQrySecAgentACIDMap(pQrySecAgentACIDMap,nRequestID);
}
int td_req_qry_product_exch_rate(tdApi a, CThostFtdcQryProductExchRateField * pQryProductExchRate, int nRequestID){
  CThostFtdcTraderApi* p = (CThostFtdcTraderApi*)a;
  return p->ReqQryProductExchRate(pQryProductExchRate,nRequestID);
}
int td_req_qry_product_group(tdApi a, CThostFtdcQryProductGroupField * pQryProductGroup, int nRequestID){
  CThostFtdcTraderApi* p = (CThostFtdcTraderApi*)a;
  return p->ReqQryProductGroup(pQryProductGroup,nRequestID);
}
int td_req_qry_m_m_instrument_commission_rate(tdApi a, CThostFtdcQryMMInstrumentCommissionRateField * pQryMMInstrumentCommissionRate, int nRequestID){
  CThostFtdcTraderApi* p = (CThostFtdcTraderApi*)a;
  return p->ReqQryMMInstrumentCommissionRate(pQryMMInstrumentCommissionRate,nRequestID);
}
int td_req_qry_m_m_option_instr_comm_rate(tdApi a, CThostFtdcQryMMOptionInstrCommRateField * pQryMMOptionInstrCommRate, int nRequestID){
  CThostFtdcTraderApi* p = (CThostFtdcTraderApi*)a;
  return p->ReqQryMMOptionInstrCommRate(pQryMMOptionInstrCommRate,nRequestID);
}
int td_req_qry_instrument_order_comm_rate(tdApi a, CThostFtdcQryInstrumentOrderCommRateField * pQryInstrumentOrderCommRate, int nRequestID){
  CThostFtdcTraderApi* p = (CThostFtdcTraderApi*)a;
  return p->ReqQryInstrumentOrderCommRate(pQryInstrumentOrderCommRate,nRequestID);
}
int td_req_qry_sec_agent_trading_account(tdApi a, CThostFtdcQryTradingAccountField * pQryTradingAccount, int nRequestID){
  CThostFtdcTraderApi* p = (CThostFtdcTraderApi*)a;
  return p->ReqQrySecAgentTradingAccount(pQryTradingAccount,nRequestID);
}
int td_req_qry_sec_agent_check_mode(tdApi a, CThostFtdcQrySecAgentCheckModeField * pQrySecAgentCheckMode, int nRequestID){
  CThostFtdcTraderApi* p = (CThostFtdcTraderApi*)a;
  return p->ReqQrySecAgentCheckMode(pQrySecAgentCheckMode,nRequestID);
}
int td_req_qry_sec_agent_trade_info(tdApi a, CThostFtdcQrySecAgentTradeInfoField * pQrySecAgentTradeInfo, int nRequestID){
  CThostFtdcTraderApi* p = (CThostFtdcTraderApi*)a;
  return p->ReqQrySecAgentTradeInfo(pQrySecAgentTradeInfo,nRequestID);
}
int td_req_qry_option_instr_trade_cost(tdApi a, CThostFtdcQryOptionInstrTradeCostField * pQryOptionInstrTradeCost, int nRequestID){
  CThostFtdcTraderApi* p = (CThostFtdcTraderApi*)a;
  return p->ReqQryOptionInstrTradeCost(pQryOptionInstrTradeCost,nRequestID);
}
int td_req_qry_option_instr_comm_rate(tdApi a, CThostFtdcQryOptionInstrCommRateField * pQryOptionInstrCommRate, int nRequestID){
  CThostFtdcTraderApi* p = (CThostFtdcTraderApi*)a;
  return p->ReqQryOptionInstrCommRate(pQryOptionInstrCommRate,nRequestID);
}
int td_req_qry_exec_order(tdApi a, CThostFtdcQryExecOrderField * pQryExecOrder, int nRequestID){
  CThostFtdcTraderApi* p = (CThostFtdcTraderApi*)a;
  return p->ReqQryExecOrder(pQryExecOrder,nRequestID);
}
int td_req_qry_for_quote(tdApi a, CThostFtdcQryForQuoteField * pQryForQuote, int nRequestID){
  CThostFtdcTraderApi* p = (CThostFtdcTraderApi*)a;
  return p->ReqQryForQuote(pQryForQuote,nRequestID);
}
int td_req_qry_quote(tdApi a, CThostFtdcQryQuoteField * pQryQuote, int nRequestID){
  CThostFtdcTraderApi* p = (CThostFtdcTraderApi*)a;
  return p->ReqQryQuote(pQryQuote,nRequestID);
}
int td_req_qry_option_self_close(tdApi a, CThostFtdcQryOptionSelfCloseField * pQryOptionSelfClose, int nRequestID){
  CThostFtdcTraderApi* p = (CThostFtdcTraderApi*)a;
  return p->ReqQryOptionSelfClose(pQryOptionSelfClose,nRequestID);
}
int td_req_qry_invest_unit(tdApi a, CThostFtdcQryInvestUnitField * pQryInvestUnit, int nRequestID){
  CThostFtdcTraderApi* p = (CThostFtdcTraderApi*)a;
  return p->ReqQryInvestUnit(pQryInvestUnit,nRequestID);
}
int td_req_qry_comb_instrument_guard(tdApi a, CThostFtdcQryCombInstrumentGuardField * pQryCombInstrumentGuard, int nRequestID){
  CThostFtdcTraderApi* p = (CThostFtdcTraderApi*)a;
  return p->ReqQryCombInstrumentGuard(pQryCombInstrumentGuard,nRequestID);
}
int td_req_qry_comb_action(tdApi a, CThostFtdcQryCombActionField * pQryCombAction, int nRequestID){
  CThostFtdcTraderApi* p = (CThostFtdcTraderApi*)a;
  return p->ReqQryCombAction(pQryCombAction,nRequestID);
}
int td_req_qry_transfer_serial(tdApi a, CThostFtdcQryTransferSerialField * pQryTransferSerial, int nRequestID){
  CThostFtdcTraderApi* p = (CThostFtdcTraderApi*)a;
  return p->ReqQryTransferSerial(pQryTransferSerial,nRequestID);
}
int td_req_qry_accountregister(tdApi a, CThostFtdcQryAccountregisterField * pQryAccountregister, int nRequestID){
  CThostFtdcTraderApi* p = (CThostFtdcTraderApi*)a;
  return p->ReqQryAccountregister(pQryAccountregister,nRequestID);
}
int td_req_qry_contract_bank(tdApi a, CThostFtdcQryContractBankField * pQryContractBank, int nRequestID){
  CThostFtdcTraderApi* p = (CThostFtdcTraderApi*)a;
  return p->ReqQryContractBank(pQryContractBank,nRequestID);
}
int td_req_qry_parked_order(tdApi a, CThostFtdcQryParkedOrderField * pQryParkedOrder, int nRequestID){
  CThostFtdcTraderApi* p = (CThostFtdcTraderApi*)a;
  return p->ReqQryParkedOrder(pQryParkedOrder,nRequestID);
}
int td_req_qry_parked_order_action(tdApi a, CThostFtdcQryParkedOrderActionField * pQryParkedOrderAction, int nRequestID){
  CThostFtdcTraderApi* p = (CThostFtdcTraderApi*)a;
  return p->ReqQryParkedOrderAction(pQryParkedOrderAction,nRequestID);
}
int td_req_qry_trading_notice(tdApi a, CThostFtdcQryTradingNoticeField * pQryTradingNotice, int nRequestID){
  CThostFtdcTraderApi* p = (CThostFtdcTraderApi*)a;
  return p->ReqQryTradingNotice(pQryTradingNotice,nRequestID);
}
int td_req_qry_broker_trading_params(tdApi a, CThostFtdcQryBrokerTradingParamsField * pQryBrokerTradingParams, int nRequestID){
  CThostFtdcTraderApi* p = (CThostFtdcTraderApi*)a;
  return p->ReqQryBrokerTradingParams(pQryBrokerTradingParams,nRequestID);
}
int td_req_qry_broker_trading_algos(tdApi a, CThostFtdcQryBrokerTradingAlgosField * pQryBrokerTradingAlgos, int nRequestID){
  CThostFtdcTraderApi* p = (CThostFtdcTraderApi*)a;
  return p->ReqQryBrokerTradingAlgos(pQryBrokerTradingAlgos,nRequestID);
}
int td_req_query_c_f_m_m_c_trading_account_token(tdApi a, CThostFtdcQueryCFMMCTradingAccountTokenField * pQueryCFMMCTradingAccountToken, int nRequestID){
  CThostFtdcTraderApi* p = (CThostFtdcTraderApi*)a;
  return p->ReqQueryCFMMCTradingAccountToken(pQueryCFMMCTradingAccountToken,nRequestID);
}
int td_req_from_bank_to_future_by_future(tdApi a, CThostFtdcReqTransferField * pReqTransfer, int nRequestID){
  CThostFtdcTraderApi* p = (CThostFtdcTraderApi*)a;
  return p->ReqFromBankToFutureByFuture(pReqTransfer,nRequestID);
}
int td_req_from_future_to_bank_by_future(tdApi a, CThostFtdcReqTransferField * pReqTransfer, int nRequestID){
  CThostFtdcTraderApi* p = (CThostFtdcTraderApi*)a;
  return p->ReqFromFutureToBankByFuture(pReqTransfer,nRequestID);
}
int td_req_query_bank_account_money_by_future(tdApi a, CThostFtdcReqQueryAccountField * pReqQueryAccount, int nRequestID){
  CThostFtdcTraderApi* p = (CThostFtdcTraderApi*)a;
  return p->ReqQueryBankAccountMoneyByFuture(pReqQueryAccount,nRequestID);
}