// This file was automatically generated by ctpgen
package ctp

//#include "gen_td_api.h"
import "C"
import "unsafe"

func CThostFtdcTraderSpiCValue(ptr CThostFtdcTraderSpi) C.tdSpi {
	v := storeGoPtr(ptr)
	p := C.td_new_spi(C.uint64_t(v))
	return p
}

type CThostFtdcTraderApi struct {
	p   C.tdApi
	spi C.tdSpi
}

func TdCreateFtdcTraderApi(pszFlowPath string) *CThostFtdcTraderApi {
	cpszFlowPath := go2cStrPtr(pszFlowPath)
	cRet := C.td_create_ftdc_trader_api(cpszFlowPath)
	ret := new(CThostFtdcTraderApi)
	ret.p = cRet
	return ret
}

func TdGetApiVersion() string {
	cRet := C.td_get_api_version()
	ret := cPtr2GoStr(cRet)
	return ret
}

func (a *CThostFtdcTraderApi) Release() {
	C.td_release(a.p)

	if a.spi != nil {
		C.td_spi_free(a.spi)
		a.spi = nil
	}
}

func (a *CThostFtdcTraderApi) Init() {
	C.td_init(a.p)

}

func (a *CThostFtdcTraderApi) Join() int {

	ret := C.td_join(a.p)

	return int(ret)
}

func (a *CThostFtdcTraderApi) GetTradingDay() string {

	ret := C.td_get_trading_day(a.p)

	return cPtr2GoStr(ret)
}

func (a *CThostFtdcTraderApi) GetFrontInfo(pFrontInfo *CThostFtdcFrontInfoField) {
	cpFrontInfo := CThostFtdcFrontInfoFieldCValue(pFrontInfo)
	defer func() {
		C.free(unsafe.Pointer(cpFrontInfo))
	}()
	C.td_get_front_info(a.p, cpFrontInfo)

}

func (a *CThostFtdcTraderApi) RegisterFront(pszFrontAddress string) {
	cpszFrontAddress := go2cStrPtr(pszFrontAddress)
	defer func() {
		freeCStr(cpszFrontAddress)
	}()
	C.td_register_front(a.p, cpszFrontAddress)

}

func (a *CThostFtdcTraderApi) RegisterNameServer(pszNsAddress string) {
	cpszNsAddress := go2cStrPtr(pszNsAddress)
	defer func() {
		freeCStr(cpszNsAddress)
	}()
	C.td_register_name_server(a.p, cpszNsAddress)

}

func (a *CThostFtdcTraderApi) RegisterFensUserInfo(pFensUserInfo *CThostFtdcFensUserInfoField) {
	cpFensUserInfo := CThostFtdcFensUserInfoFieldCValue(pFensUserInfo)
	defer func() {
		C.free(unsafe.Pointer(cpFensUserInfo))
	}()
	C.td_register_fens_user_info(a.p, cpFensUserInfo)

}

func (a *CThostFtdcTraderApi) RegisterSpi(pSpi CThostFtdcTraderSpi) {
	cpSpi := CThostFtdcTraderSpiCValue(pSpi)
	C.td_register_spi(a.p, cpSpi)

	if a.spi != nil {
		C.td_spi_free(a.spi)
	}
	a.spi = cpSpi
}

func (a *CThostFtdcTraderApi) SubscribePrivateTopic(nResumeType THOST_TE_RESUME_TYPE) {
	cnResumeType := C.THOST_TE_RESUME_TYPE(nResumeType)
	C.td_subscribe_private_topic(a.p, cnResumeType)

}

func (a *CThostFtdcTraderApi) SubscribePublicTopic(nResumeType THOST_TE_RESUME_TYPE) {
	cnResumeType := C.THOST_TE_RESUME_TYPE(nResumeType)
	C.td_subscribe_public_topic(a.p, cnResumeType)

}

func (a *CThostFtdcTraderApi) ReqAuthenticate(pReqAuthenticateField *CThostFtdcReqAuthenticateField, nRequestID int) int {
	cpReqAuthenticateField := CThostFtdcReqAuthenticateFieldCValue(pReqAuthenticateField)
	defer func() {
		C.free(unsafe.Pointer(cpReqAuthenticateField))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_authenticate(a.p, cpReqAuthenticateField, cnRequestID)

	return int(ret)
}

func (a *CThostFtdcTraderApi) RegisterUserSystemInfo(pUserSystemInfo *CThostFtdcUserSystemInfoField) int {
	cpUserSystemInfo := CThostFtdcUserSystemInfoFieldCValue(pUserSystemInfo)
	defer func() {
		C.free(unsafe.Pointer(cpUserSystemInfo))
	}()

	ret := C.td_register_user_system_info(a.p, cpUserSystemInfo)

	return int(ret)
}

func (a *CThostFtdcTraderApi) SubmitUserSystemInfo(pUserSystemInfo *CThostFtdcUserSystemInfoField) int {
	cpUserSystemInfo := CThostFtdcUserSystemInfoFieldCValue(pUserSystemInfo)
	defer func() {
		C.free(unsafe.Pointer(cpUserSystemInfo))
	}()

	ret := C.td_submit_user_system_info(a.p, cpUserSystemInfo)

	return int(ret)
}

func (a *CThostFtdcTraderApi) ReqUserLogin(pReqUserLoginField *CThostFtdcReqUserLoginField, nRequestID int) int {
	cpReqUserLoginField := CThostFtdcReqUserLoginFieldCValue(pReqUserLoginField)
	defer func() {
		C.free(unsafe.Pointer(cpReqUserLoginField))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_user_login(a.p, cpReqUserLoginField, cnRequestID)

	return int(ret)
}

func (a *CThostFtdcTraderApi) ReqUserLogout(pUserLogout *CThostFtdcUserLogoutField, nRequestID int) int {
	cpUserLogout := CThostFtdcUserLogoutFieldCValue(pUserLogout)
	defer func() {
		C.free(unsafe.Pointer(cpUserLogout))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_user_logout(a.p, cpUserLogout, cnRequestID)

	return int(ret)
}

func (a *CThostFtdcTraderApi) ReqUserPasswordUpdate(pUserPasswordUpdate *CThostFtdcUserPasswordUpdateField, nRequestID int) int {
	cpUserPasswordUpdate := CThostFtdcUserPasswordUpdateFieldCValue(pUserPasswordUpdate)
	defer func() {
		C.free(unsafe.Pointer(cpUserPasswordUpdate))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_user_password_update(a.p, cpUserPasswordUpdate, cnRequestID)

	return int(ret)
}

func (a *CThostFtdcTraderApi) ReqTradingAccountPasswordUpdate(pTradingAccountPasswordUpdate *CThostFtdcTradingAccountPasswordUpdateField, nRequestID int) int {
	cpTradingAccountPasswordUpdate := CThostFtdcTradingAccountPasswordUpdateFieldCValue(pTradingAccountPasswordUpdate)
	defer func() {
		C.free(unsafe.Pointer(cpTradingAccountPasswordUpdate))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_trading_account_password_update(a.p, cpTradingAccountPasswordUpdate, cnRequestID)

	return int(ret)
}

func (a *CThostFtdcTraderApi) ReqUserAuthMethod(pReqUserAuthMethod *CThostFtdcReqUserAuthMethodField, nRequestID int) int {
	cpReqUserAuthMethod := CThostFtdcReqUserAuthMethodFieldCValue(pReqUserAuthMethod)
	defer func() {
		C.free(unsafe.Pointer(cpReqUserAuthMethod))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_user_auth_method(a.p, cpReqUserAuthMethod, cnRequestID)

	return int(ret)
}

func (a *CThostFtdcTraderApi) ReqGenUserCaptcha(pReqGenUserCaptcha *CThostFtdcReqGenUserCaptchaField, nRequestID int) int {
	cpReqGenUserCaptcha := CThostFtdcReqGenUserCaptchaFieldCValue(pReqGenUserCaptcha)
	defer func() {
		C.free(unsafe.Pointer(cpReqGenUserCaptcha))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_gen_user_captcha(a.p, cpReqGenUserCaptcha, cnRequestID)

	return int(ret)
}

func (a *CThostFtdcTraderApi) ReqGenUserText(pReqGenUserText *CThostFtdcReqGenUserTextField, nRequestID int) int {
	cpReqGenUserText := CThostFtdcReqGenUserTextFieldCValue(pReqGenUserText)
	defer func() {
		C.free(unsafe.Pointer(cpReqGenUserText))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_gen_user_text(a.p, cpReqGenUserText, cnRequestID)

	return int(ret)
}

func (a *CThostFtdcTraderApi) ReqUserLoginWithCaptcha(pReqUserLoginWithCaptcha *CThostFtdcReqUserLoginWithCaptchaField, nRequestID int) int {
	cpReqUserLoginWithCaptcha := CThostFtdcReqUserLoginWithCaptchaFieldCValue(pReqUserLoginWithCaptcha)
	defer func() {
		C.free(unsafe.Pointer(cpReqUserLoginWithCaptcha))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_user_login_with_captcha(a.p, cpReqUserLoginWithCaptcha, cnRequestID)

	return int(ret)
}

func (a *CThostFtdcTraderApi) ReqUserLoginWithText(pReqUserLoginWithText *CThostFtdcReqUserLoginWithTextField, nRequestID int) int {
	cpReqUserLoginWithText := CThostFtdcReqUserLoginWithTextFieldCValue(pReqUserLoginWithText)
	defer func() {
		C.free(unsafe.Pointer(cpReqUserLoginWithText))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_user_login_with_text(a.p, cpReqUserLoginWithText, cnRequestID)

	return int(ret)
}

func (a *CThostFtdcTraderApi) ReqUserLoginWithOTP(pReqUserLoginWithOTP *CThostFtdcReqUserLoginWithOTPField, nRequestID int) int {
	cpReqUserLoginWithOTP := CThostFtdcReqUserLoginWithOTPFieldCValue(pReqUserLoginWithOTP)
	defer func() {
		C.free(unsafe.Pointer(cpReqUserLoginWithOTP))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_user_login_with_o_t_p(a.p, cpReqUserLoginWithOTP, cnRequestID)

	return int(ret)
}

func (a *CThostFtdcTraderApi) ReqOrderInsert(pInputOrder *CThostFtdcInputOrderField, nRequestID int) int {
	cpInputOrder := CThostFtdcInputOrderFieldCValue(pInputOrder)
	defer func() {
		C.free(unsafe.Pointer(cpInputOrder))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_order_insert(a.p, cpInputOrder, cnRequestID)

	return int(ret)
}

func (a *CThostFtdcTraderApi) ReqParkedOrderInsert(pParkedOrder *CThostFtdcParkedOrderField, nRequestID int) int {
	cpParkedOrder := CThostFtdcParkedOrderFieldCValue(pParkedOrder)
	defer func() {
		C.free(unsafe.Pointer(cpParkedOrder))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_parked_order_insert(a.p, cpParkedOrder, cnRequestID)

	return int(ret)
}

func (a *CThostFtdcTraderApi) ReqParkedOrderAction(pParkedOrderAction *CThostFtdcParkedOrderActionField, nRequestID int) int {
	cpParkedOrderAction := CThostFtdcParkedOrderActionFieldCValue(pParkedOrderAction)
	defer func() {
		C.free(unsafe.Pointer(cpParkedOrderAction))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_parked_order_action(a.p, cpParkedOrderAction, cnRequestID)

	return int(ret)
}

func (a *CThostFtdcTraderApi) ReqOrderAction(pInputOrderAction *CThostFtdcInputOrderActionField, nRequestID int) int {
	cpInputOrderAction := CThostFtdcInputOrderActionFieldCValue(pInputOrderAction)
	defer func() {
		C.free(unsafe.Pointer(cpInputOrderAction))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_order_action(a.p, cpInputOrderAction, cnRequestID)

	return int(ret)
}

func (a *CThostFtdcTraderApi) ReqQryMaxOrderVolume(pQryMaxOrderVolume *CThostFtdcQryMaxOrderVolumeField, nRequestID int) int {
	cpQryMaxOrderVolume := CThostFtdcQryMaxOrderVolumeFieldCValue(pQryMaxOrderVolume)
	defer func() {
		C.free(unsafe.Pointer(cpQryMaxOrderVolume))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_qry_max_order_volume(a.p, cpQryMaxOrderVolume, cnRequestID)

	return int(ret)
}

func (a *CThostFtdcTraderApi) ReqSettlementInfoConfirm(pSettlementInfoConfirm *CThostFtdcSettlementInfoConfirmField, nRequestID int) int {
	cpSettlementInfoConfirm := CThostFtdcSettlementInfoConfirmFieldCValue(pSettlementInfoConfirm)
	defer func() {
		C.free(unsafe.Pointer(cpSettlementInfoConfirm))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_settlement_info_confirm(a.p, cpSettlementInfoConfirm, cnRequestID)

	return int(ret)
}

func (a *CThostFtdcTraderApi) ReqRemoveParkedOrder(pRemoveParkedOrder *CThostFtdcRemoveParkedOrderField, nRequestID int) int {
	cpRemoveParkedOrder := CThostFtdcRemoveParkedOrderFieldCValue(pRemoveParkedOrder)
	defer func() {
		C.free(unsafe.Pointer(cpRemoveParkedOrder))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_remove_parked_order(a.p, cpRemoveParkedOrder, cnRequestID)

	return int(ret)
}

func (a *CThostFtdcTraderApi) ReqRemoveParkedOrderAction(pRemoveParkedOrderAction *CThostFtdcRemoveParkedOrderActionField, nRequestID int) int {
	cpRemoveParkedOrderAction := CThostFtdcRemoveParkedOrderActionFieldCValue(pRemoveParkedOrderAction)
	defer func() {
		C.free(unsafe.Pointer(cpRemoveParkedOrderAction))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_remove_parked_order_action(a.p, cpRemoveParkedOrderAction, cnRequestID)

	return int(ret)
}

func (a *CThostFtdcTraderApi) ReqExecOrderInsert(pInputExecOrder *CThostFtdcInputExecOrderField, nRequestID int) int {
	cpInputExecOrder := CThostFtdcInputExecOrderFieldCValue(pInputExecOrder)
	defer func() {
		C.free(unsafe.Pointer(cpInputExecOrder))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_exec_order_insert(a.p, cpInputExecOrder, cnRequestID)

	return int(ret)
}

func (a *CThostFtdcTraderApi) ReqExecOrderAction(pInputExecOrderAction *CThostFtdcInputExecOrderActionField, nRequestID int) int {
	cpInputExecOrderAction := CThostFtdcInputExecOrderActionFieldCValue(pInputExecOrderAction)
	defer func() {
		C.free(unsafe.Pointer(cpInputExecOrderAction))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_exec_order_action(a.p, cpInputExecOrderAction, cnRequestID)

	return int(ret)
}

func (a *CThostFtdcTraderApi) ReqForQuoteInsert(pInputForQuote *CThostFtdcInputForQuoteField, nRequestID int) int {
	cpInputForQuote := CThostFtdcInputForQuoteFieldCValue(pInputForQuote)
	defer func() {
		C.free(unsafe.Pointer(cpInputForQuote))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_for_quote_insert(a.p, cpInputForQuote, cnRequestID)

	return int(ret)
}

func (a *CThostFtdcTraderApi) ReqQuoteInsert(pInputQuote *CThostFtdcInputQuoteField, nRequestID int) int {
	cpInputQuote := CThostFtdcInputQuoteFieldCValue(pInputQuote)
	defer func() {
		C.free(unsafe.Pointer(cpInputQuote))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_quote_insert(a.p, cpInputQuote, cnRequestID)

	return int(ret)
}

func (a *CThostFtdcTraderApi) ReqQuoteAction(pInputQuoteAction *CThostFtdcInputQuoteActionField, nRequestID int) int {
	cpInputQuoteAction := CThostFtdcInputQuoteActionFieldCValue(pInputQuoteAction)
	defer func() {
		C.free(unsafe.Pointer(cpInputQuoteAction))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_quote_action(a.p, cpInputQuoteAction, cnRequestID)

	return int(ret)
}

func (a *CThostFtdcTraderApi) ReqBatchOrderAction(pInputBatchOrderAction *CThostFtdcInputBatchOrderActionField, nRequestID int) int {
	cpInputBatchOrderAction := CThostFtdcInputBatchOrderActionFieldCValue(pInputBatchOrderAction)
	defer func() {
		C.free(unsafe.Pointer(cpInputBatchOrderAction))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_batch_order_action(a.p, cpInputBatchOrderAction, cnRequestID)

	return int(ret)
}

func (a *CThostFtdcTraderApi) ReqOptionSelfCloseInsert(pInputOptionSelfClose *CThostFtdcInputOptionSelfCloseField, nRequestID int) int {
	cpInputOptionSelfClose := CThostFtdcInputOptionSelfCloseFieldCValue(pInputOptionSelfClose)
	defer func() {
		C.free(unsafe.Pointer(cpInputOptionSelfClose))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_option_self_close_insert(a.p, cpInputOptionSelfClose, cnRequestID)

	return int(ret)
}

func (a *CThostFtdcTraderApi) ReqOptionSelfCloseAction(pInputOptionSelfCloseAction *CThostFtdcInputOptionSelfCloseActionField, nRequestID int) int {
	cpInputOptionSelfCloseAction := CThostFtdcInputOptionSelfCloseActionFieldCValue(pInputOptionSelfCloseAction)
	defer func() {
		C.free(unsafe.Pointer(cpInputOptionSelfCloseAction))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_option_self_close_action(a.p, cpInputOptionSelfCloseAction, cnRequestID)

	return int(ret)
}

func (a *CThostFtdcTraderApi) ReqCombActionInsert(pInputCombAction *CThostFtdcInputCombActionField, nRequestID int) int {
	cpInputCombAction := CThostFtdcInputCombActionFieldCValue(pInputCombAction)
	defer func() {
		C.free(unsafe.Pointer(cpInputCombAction))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_comb_action_insert(a.p, cpInputCombAction, cnRequestID)

	return int(ret)
}

func (a *CThostFtdcTraderApi) ReqQryOrder(pQryOrder *CThostFtdcQryOrderField, nRequestID int) int {
	cpQryOrder := CThostFtdcQryOrderFieldCValue(pQryOrder)
	defer func() {
		C.free(unsafe.Pointer(cpQryOrder))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_qry_order(a.p, cpQryOrder, cnRequestID)

	return int(ret)
}

func (a *CThostFtdcTraderApi) ReqQryTrade(pQryTrade *CThostFtdcQryTradeField, nRequestID int) int {
	cpQryTrade := CThostFtdcQryTradeFieldCValue(pQryTrade)
	defer func() {
		C.free(unsafe.Pointer(cpQryTrade))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_qry_trade(a.p, cpQryTrade, cnRequestID)

	return int(ret)
}

func (a *CThostFtdcTraderApi) ReqQryInvestorPosition(pQryInvestorPosition *CThostFtdcQryInvestorPositionField, nRequestID int) int {
	cpQryInvestorPosition := CThostFtdcQryInvestorPositionFieldCValue(pQryInvestorPosition)
	defer func() {
		C.free(unsafe.Pointer(cpQryInvestorPosition))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_qry_investor_position(a.p, cpQryInvestorPosition, cnRequestID)

	return int(ret)
}

func (a *CThostFtdcTraderApi) ReqQryTradingAccount(pQryTradingAccount *CThostFtdcQryTradingAccountField, nRequestID int) int {
	cpQryTradingAccount := CThostFtdcQryTradingAccountFieldCValue(pQryTradingAccount)
	defer func() {
		C.free(unsafe.Pointer(cpQryTradingAccount))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_qry_trading_account(a.p, cpQryTradingAccount, cnRequestID)

	return int(ret)
}

func (a *CThostFtdcTraderApi) ReqQryInvestor(pQryInvestor *CThostFtdcQryInvestorField, nRequestID int) int {
	cpQryInvestor := CThostFtdcQryInvestorFieldCValue(pQryInvestor)
	defer func() {
		C.free(unsafe.Pointer(cpQryInvestor))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_qry_investor(a.p, cpQryInvestor, cnRequestID)

	return int(ret)
}

func (a *CThostFtdcTraderApi) ReqQryTradingCode(pQryTradingCode *CThostFtdcQryTradingCodeField, nRequestID int) int {
	cpQryTradingCode := CThostFtdcQryTradingCodeFieldCValue(pQryTradingCode)
	defer func() {
		C.free(unsafe.Pointer(cpQryTradingCode))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_qry_trading_code(a.p, cpQryTradingCode, cnRequestID)

	return int(ret)
}

func (a *CThostFtdcTraderApi) ReqQryInstrumentMarginRate(pQryInstrumentMarginRate *CThostFtdcQryInstrumentMarginRateField, nRequestID int) int {
	cpQryInstrumentMarginRate := CThostFtdcQryInstrumentMarginRateFieldCValue(pQryInstrumentMarginRate)
	defer func() {
		C.free(unsafe.Pointer(cpQryInstrumentMarginRate))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_qry_instrument_margin_rate(a.p, cpQryInstrumentMarginRate, cnRequestID)

	return int(ret)
}

func (a *CThostFtdcTraderApi) ReqQryInstrumentCommissionRate(pQryInstrumentCommissionRate *CThostFtdcQryInstrumentCommissionRateField, nRequestID int) int {
	cpQryInstrumentCommissionRate := CThostFtdcQryInstrumentCommissionRateFieldCValue(pQryInstrumentCommissionRate)
	defer func() {
		C.free(unsafe.Pointer(cpQryInstrumentCommissionRate))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_qry_instrument_commission_rate(a.p, cpQryInstrumentCommissionRate, cnRequestID)

	return int(ret)
}

func (a *CThostFtdcTraderApi) ReqQryExchange(pQryExchange *CThostFtdcQryExchangeField, nRequestID int) int {
	cpQryExchange := CThostFtdcQryExchangeFieldCValue(pQryExchange)
	defer func() {
		C.free(unsafe.Pointer(cpQryExchange))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_qry_exchange(a.p, cpQryExchange, cnRequestID)

	return int(ret)
}

func (a *CThostFtdcTraderApi) ReqQryProduct(pQryProduct *CThostFtdcQryProductField, nRequestID int) int {
	cpQryProduct := CThostFtdcQryProductFieldCValue(pQryProduct)
	defer func() {
		C.free(unsafe.Pointer(cpQryProduct))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_qry_product(a.p, cpQryProduct, cnRequestID)

	return int(ret)
}

func (a *CThostFtdcTraderApi) ReqQryInstrument(pQryInstrument *CThostFtdcQryInstrumentField, nRequestID int) int {
	cpQryInstrument := CThostFtdcQryInstrumentFieldCValue(pQryInstrument)
	defer func() {
		C.free(unsafe.Pointer(cpQryInstrument))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_qry_instrument(a.p, cpQryInstrument, cnRequestID)

	return int(ret)
}

func (a *CThostFtdcTraderApi) ReqQryDepthMarketData(pQryDepthMarketData *CThostFtdcQryDepthMarketDataField, nRequestID int) int {
	cpQryDepthMarketData := CThostFtdcQryDepthMarketDataFieldCValue(pQryDepthMarketData)
	defer func() {
		C.free(unsafe.Pointer(cpQryDepthMarketData))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_qry_depth_market_data(a.p, cpQryDepthMarketData, cnRequestID)

	return int(ret)
}

func (a *CThostFtdcTraderApi) ReqQryTraderOffer(pQryTraderOffer *CThostFtdcQryTraderOfferField, nRequestID int) int {
	cpQryTraderOffer := CThostFtdcQryTraderOfferFieldCValue(pQryTraderOffer)
	defer func() {
		C.free(unsafe.Pointer(cpQryTraderOffer))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_qry_trader_offer(a.p, cpQryTraderOffer, cnRequestID)

	return int(ret)
}

func (a *CThostFtdcTraderApi) ReqQrySettlementInfo(pQrySettlementInfo *CThostFtdcQrySettlementInfoField, nRequestID int) int {
	cpQrySettlementInfo := CThostFtdcQrySettlementInfoFieldCValue(pQrySettlementInfo)
	defer func() {
		C.free(unsafe.Pointer(cpQrySettlementInfo))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_qry_settlement_info(a.p, cpQrySettlementInfo, cnRequestID)

	return int(ret)
}

func (a *CThostFtdcTraderApi) ReqQryTransferBank(pQryTransferBank *CThostFtdcQryTransferBankField, nRequestID int) int {
	cpQryTransferBank := CThostFtdcQryTransferBankFieldCValue(pQryTransferBank)
	defer func() {
		C.free(unsafe.Pointer(cpQryTransferBank))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_qry_transfer_bank(a.p, cpQryTransferBank, cnRequestID)

	return int(ret)
}

func (a *CThostFtdcTraderApi) ReqQryInvestorPositionDetail(pQryInvestorPositionDetail *CThostFtdcQryInvestorPositionDetailField, nRequestID int) int {
	cpQryInvestorPositionDetail := CThostFtdcQryInvestorPositionDetailFieldCValue(pQryInvestorPositionDetail)
	defer func() {
		C.free(unsafe.Pointer(cpQryInvestorPositionDetail))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_qry_investor_position_detail(a.p, cpQryInvestorPositionDetail, cnRequestID)

	return int(ret)
}

func (a *CThostFtdcTraderApi) ReqQryNotice(pQryNotice *CThostFtdcQryNoticeField, nRequestID int) int {
	cpQryNotice := CThostFtdcQryNoticeFieldCValue(pQryNotice)
	defer func() {
		C.free(unsafe.Pointer(cpQryNotice))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_qry_notice(a.p, cpQryNotice, cnRequestID)

	return int(ret)
}

func (a *CThostFtdcTraderApi) ReqQrySettlementInfoConfirm(pQrySettlementInfoConfirm *CThostFtdcQrySettlementInfoConfirmField, nRequestID int) int {
	cpQrySettlementInfoConfirm := CThostFtdcQrySettlementInfoConfirmFieldCValue(pQrySettlementInfoConfirm)
	defer func() {
		C.free(unsafe.Pointer(cpQrySettlementInfoConfirm))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_qry_settlement_info_confirm(a.p, cpQrySettlementInfoConfirm, cnRequestID)

	return int(ret)
}

func (a *CThostFtdcTraderApi) ReqQryInvestorPositionCombineDetail(pQryInvestorPositionCombineDetail *CThostFtdcQryInvestorPositionCombineDetailField, nRequestID int) int {
	cpQryInvestorPositionCombineDetail := CThostFtdcQryInvestorPositionCombineDetailFieldCValue(pQryInvestorPositionCombineDetail)
	defer func() {
		C.free(unsafe.Pointer(cpQryInvestorPositionCombineDetail))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_qry_investor_position_combine_detail(a.p, cpQryInvestorPositionCombineDetail, cnRequestID)

	return int(ret)
}

func (a *CThostFtdcTraderApi) ReqQryCFMMCTradingAccountKey(pQryCFMMCTradingAccountKey *CThostFtdcQryCFMMCTradingAccountKeyField, nRequestID int) int {
	cpQryCFMMCTradingAccountKey := CThostFtdcQryCFMMCTradingAccountKeyFieldCValue(pQryCFMMCTradingAccountKey)
	defer func() {
		C.free(unsafe.Pointer(cpQryCFMMCTradingAccountKey))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_qry_c_f_m_m_c_trading_account_key(a.p, cpQryCFMMCTradingAccountKey, cnRequestID)

	return int(ret)
}

func (a *CThostFtdcTraderApi) ReqQryEWarrantOffset(pQryEWarrantOffset *CThostFtdcQryEWarrantOffsetField, nRequestID int) int {
	cpQryEWarrantOffset := CThostFtdcQryEWarrantOffsetFieldCValue(pQryEWarrantOffset)
	defer func() {
		C.free(unsafe.Pointer(cpQryEWarrantOffset))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_qry_e_warrant_offset(a.p, cpQryEWarrantOffset, cnRequestID)

	return int(ret)
}

func (a *CThostFtdcTraderApi) ReqQryInvestorProductGroupMargin(pQryInvestorProductGroupMargin *CThostFtdcQryInvestorProductGroupMarginField, nRequestID int) int {
	cpQryInvestorProductGroupMargin := CThostFtdcQryInvestorProductGroupMarginFieldCValue(pQryInvestorProductGroupMargin)
	defer func() {
		C.free(unsafe.Pointer(cpQryInvestorProductGroupMargin))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_qry_investor_product_group_margin(a.p, cpQryInvestorProductGroupMargin, cnRequestID)

	return int(ret)
}

func (a *CThostFtdcTraderApi) ReqQryExchangeMarginRate(pQryExchangeMarginRate *CThostFtdcQryExchangeMarginRateField, nRequestID int) int {
	cpQryExchangeMarginRate := CThostFtdcQryExchangeMarginRateFieldCValue(pQryExchangeMarginRate)
	defer func() {
		C.free(unsafe.Pointer(cpQryExchangeMarginRate))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_qry_exchange_margin_rate(a.p, cpQryExchangeMarginRate, cnRequestID)

	return int(ret)
}

func (a *CThostFtdcTraderApi) ReqQryExchangeMarginRateAdjust(pQryExchangeMarginRateAdjust *CThostFtdcQryExchangeMarginRateAdjustField, nRequestID int) int {
	cpQryExchangeMarginRateAdjust := CThostFtdcQryExchangeMarginRateAdjustFieldCValue(pQryExchangeMarginRateAdjust)
	defer func() {
		C.free(unsafe.Pointer(cpQryExchangeMarginRateAdjust))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_qry_exchange_margin_rate_adjust(a.p, cpQryExchangeMarginRateAdjust, cnRequestID)

	return int(ret)
}

func (a *CThostFtdcTraderApi) ReqQryExchangeRate(pQryExchangeRate *CThostFtdcQryExchangeRateField, nRequestID int) int {
	cpQryExchangeRate := CThostFtdcQryExchangeRateFieldCValue(pQryExchangeRate)
	defer func() {
		C.free(unsafe.Pointer(cpQryExchangeRate))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_qry_exchange_rate(a.p, cpQryExchangeRate, cnRequestID)

	return int(ret)
}

func (a *CThostFtdcTraderApi) ReqQrySecAgentACIDMap(pQrySecAgentACIDMap *CThostFtdcQrySecAgentACIDMapField, nRequestID int) int {
	cpQrySecAgentACIDMap := CThostFtdcQrySecAgentACIDMapFieldCValue(pQrySecAgentACIDMap)
	defer func() {
		C.free(unsafe.Pointer(cpQrySecAgentACIDMap))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_qry_sec_agent_a_c_i_d_map(a.p, cpQrySecAgentACIDMap, cnRequestID)

	return int(ret)
}

func (a *CThostFtdcTraderApi) ReqQryProductExchRate(pQryProductExchRate *CThostFtdcQryProductExchRateField, nRequestID int) int {
	cpQryProductExchRate := CThostFtdcQryProductExchRateFieldCValue(pQryProductExchRate)
	defer func() {
		C.free(unsafe.Pointer(cpQryProductExchRate))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_qry_product_exch_rate(a.p, cpQryProductExchRate, cnRequestID)

	return int(ret)
}

func (a *CThostFtdcTraderApi) ReqQryProductGroup(pQryProductGroup *CThostFtdcQryProductGroupField, nRequestID int) int {
	cpQryProductGroup := CThostFtdcQryProductGroupFieldCValue(pQryProductGroup)
	defer func() {
		C.free(unsafe.Pointer(cpQryProductGroup))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_qry_product_group(a.p, cpQryProductGroup, cnRequestID)

	return int(ret)
}

func (a *CThostFtdcTraderApi) ReqQryMMInstrumentCommissionRate(pQryMMInstrumentCommissionRate *CThostFtdcQryMMInstrumentCommissionRateField, nRequestID int) int {
	cpQryMMInstrumentCommissionRate := CThostFtdcQryMMInstrumentCommissionRateFieldCValue(pQryMMInstrumentCommissionRate)
	defer func() {
		C.free(unsafe.Pointer(cpQryMMInstrumentCommissionRate))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_qry_m_m_instrument_commission_rate(a.p, cpQryMMInstrumentCommissionRate, cnRequestID)

	return int(ret)
}

func (a *CThostFtdcTraderApi) ReqQryMMOptionInstrCommRate(pQryMMOptionInstrCommRate *CThostFtdcQryMMOptionInstrCommRateField, nRequestID int) int {
	cpQryMMOptionInstrCommRate := CThostFtdcQryMMOptionInstrCommRateFieldCValue(pQryMMOptionInstrCommRate)
	defer func() {
		C.free(unsafe.Pointer(cpQryMMOptionInstrCommRate))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_qry_m_m_option_instr_comm_rate(a.p, cpQryMMOptionInstrCommRate, cnRequestID)

	return int(ret)
}

func (a *CThostFtdcTraderApi) ReqQryInstrumentOrderCommRate(pQryInstrumentOrderCommRate *CThostFtdcQryInstrumentOrderCommRateField, nRequestID int) int {
	cpQryInstrumentOrderCommRate := CThostFtdcQryInstrumentOrderCommRateFieldCValue(pQryInstrumentOrderCommRate)
	defer func() {
		C.free(unsafe.Pointer(cpQryInstrumentOrderCommRate))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_qry_instrument_order_comm_rate(a.p, cpQryInstrumentOrderCommRate, cnRequestID)

	return int(ret)
}

func (a *CThostFtdcTraderApi) ReqQrySecAgentTradingAccount(pQryTradingAccount *CThostFtdcQryTradingAccountField, nRequestID int) int {
	cpQryTradingAccount := CThostFtdcQryTradingAccountFieldCValue(pQryTradingAccount)
	defer func() {
		C.free(unsafe.Pointer(cpQryTradingAccount))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_qry_sec_agent_trading_account(a.p, cpQryTradingAccount, cnRequestID)

	return int(ret)
}

func (a *CThostFtdcTraderApi) ReqQrySecAgentCheckMode(pQrySecAgentCheckMode *CThostFtdcQrySecAgentCheckModeField, nRequestID int) int {
	cpQrySecAgentCheckMode := CThostFtdcQrySecAgentCheckModeFieldCValue(pQrySecAgentCheckMode)
	defer func() {
		C.free(unsafe.Pointer(cpQrySecAgentCheckMode))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_qry_sec_agent_check_mode(a.p, cpQrySecAgentCheckMode, cnRequestID)

	return int(ret)
}

func (a *CThostFtdcTraderApi) ReqQrySecAgentTradeInfo(pQrySecAgentTradeInfo *CThostFtdcQrySecAgentTradeInfoField, nRequestID int) int {
	cpQrySecAgentTradeInfo := CThostFtdcQrySecAgentTradeInfoFieldCValue(pQrySecAgentTradeInfo)
	defer func() {
		C.free(unsafe.Pointer(cpQrySecAgentTradeInfo))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_qry_sec_agent_trade_info(a.p, cpQrySecAgentTradeInfo, cnRequestID)

	return int(ret)
}

func (a *CThostFtdcTraderApi) ReqQryOptionInstrTradeCost(pQryOptionInstrTradeCost *CThostFtdcQryOptionInstrTradeCostField, nRequestID int) int {
	cpQryOptionInstrTradeCost := CThostFtdcQryOptionInstrTradeCostFieldCValue(pQryOptionInstrTradeCost)
	defer func() {
		C.free(unsafe.Pointer(cpQryOptionInstrTradeCost))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_qry_option_instr_trade_cost(a.p, cpQryOptionInstrTradeCost, cnRequestID)

	return int(ret)
}

func (a *CThostFtdcTraderApi) ReqQryOptionInstrCommRate(pQryOptionInstrCommRate *CThostFtdcQryOptionInstrCommRateField, nRequestID int) int {
	cpQryOptionInstrCommRate := CThostFtdcQryOptionInstrCommRateFieldCValue(pQryOptionInstrCommRate)
	defer func() {
		C.free(unsafe.Pointer(cpQryOptionInstrCommRate))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_qry_option_instr_comm_rate(a.p, cpQryOptionInstrCommRate, cnRequestID)

	return int(ret)
}

func (a *CThostFtdcTraderApi) ReqQryExecOrder(pQryExecOrder *CThostFtdcQryExecOrderField, nRequestID int) int {
	cpQryExecOrder := CThostFtdcQryExecOrderFieldCValue(pQryExecOrder)
	defer func() {
		C.free(unsafe.Pointer(cpQryExecOrder))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_qry_exec_order(a.p, cpQryExecOrder, cnRequestID)

	return int(ret)
}

func (a *CThostFtdcTraderApi) ReqQryForQuote(pQryForQuote *CThostFtdcQryForQuoteField, nRequestID int) int {
	cpQryForQuote := CThostFtdcQryForQuoteFieldCValue(pQryForQuote)
	defer func() {
		C.free(unsafe.Pointer(cpQryForQuote))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_qry_for_quote(a.p, cpQryForQuote, cnRequestID)

	return int(ret)
}

func (a *CThostFtdcTraderApi) ReqQryQuote(pQryQuote *CThostFtdcQryQuoteField, nRequestID int) int {
	cpQryQuote := CThostFtdcQryQuoteFieldCValue(pQryQuote)
	defer func() {
		C.free(unsafe.Pointer(cpQryQuote))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_qry_quote(a.p, cpQryQuote, cnRequestID)

	return int(ret)
}

func (a *CThostFtdcTraderApi) ReqQryOptionSelfClose(pQryOptionSelfClose *CThostFtdcQryOptionSelfCloseField, nRequestID int) int {
	cpQryOptionSelfClose := CThostFtdcQryOptionSelfCloseFieldCValue(pQryOptionSelfClose)
	defer func() {
		C.free(unsafe.Pointer(cpQryOptionSelfClose))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_qry_option_self_close(a.p, cpQryOptionSelfClose, cnRequestID)

	return int(ret)
}

func (a *CThostFtdcTraderApi) ReqQryInvestUnit(pQryInvestUnit *CThostFtdcQryInvestUnitField, nRequestID int) int {
	cpQryInvestUnit := CThostFtdcQryInvestUnitFieldCValue(pQryInvestUnit)
	defer func() {
		C.free(unsafe.Pointer(cpQryInvestUnit))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_qry_invest_unit(a.p, cpQryInvestUnit, cnRequestID)

	return int(ret)
}

func (a *CThostFtdcTraderApi) ReqQryCombInstrumentGuard(pQryCombInstrumentGuard *CThostFtdcQryCombInstrumentGuardField, nRequestID int) int {
	cpQryCombInstrumentGuard := CThostFtdcQryCombInstrumentGuardFieldCValue(pQryCombInstrumentGuard)
	defer func() {
		C.free(unsafe.Pointer(cpQryCombInstrumentGuard))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_qry_comb_instrument_guard(a.p, cpQryCombInstrumentGuard, cnRequestID)

	return int(ret)
}

func (a *CThostFtdcTraderApi) ReqQryCombAction(pQryCombAction *CThostFtdcQryCombActionField, nRequestID int) int {
	cpQryCombAction := CThostFtdcQryCombActionFieldCValue(pQryCombAction)
	defer func() {
		C.free(unsafe.Pointer(cpQryCombAction))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_qry_comb_action(a.p, cpQryCombAction, cnRequestID)

	return int(ret)
}

func (a *CThostFtdcTraderApi) ReqQryTransferSerial(pQryTransferSerial *CThostFtdcQryTransferSerialField, nRequestID int) int {
	cpQryTransferSerial := CThostFtdcQryTransferSerialFieldCValue(pQryTransferSerial)
	defer func() {
		C.free(unsafe.Pointer(cpQryTransferSerial))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_qry_transfer_serial(a.p, cpQryTransferSerial, cnRequestID)

	return int(ret)
}

func (a *CThostFtdcTraderApi) ReqQryAccountregister(pQryAccountregister *CThostFtdcQryAccountregisterField, nRequestID int) int {
	cpQryAccountregister := CThostFtdcQryAccountregisterFieldCValue(pQryAccountregister)
	defer func() {
		C.free(unsafe.Pointer(cpQryAccountregister))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_qry_accountregister(a.p, cpQryAccountregister, cnRequestID)

	return int(ret)
}

func (a *CThostFtdcTraderApi) ReqQryContractBank(pQryContractBank *CThostFtdcQryContractBankField, nRequestID int) int {
	cpQryContractBank := CThostFtdcQryContractBankFieldCValue(pQryContractBank)
	defer func() {
		C.free(unsafe.Pointer(cpQryContractBank))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_qry_contract_bank(a.p, cpQryContractBank, cnRequestID)

	return int(ret)
}

func (a *CThostFtdcTraderApi) ReqQryParkedOrder(pQryParkedOrder *CThostFtdcQryParkedOrderField, nRequestID int) int {
	cpQryParkedOrder := CThostFtdcQryParkedOrderFieldCValue(pQryParkedOrder)
	defer func() {
		C.free(unsafe.Pointer(cpQryParkedOrder))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_qry_parked_order(a.p, cpQryParkedOrder, cnRequestID)

	return int(ret)
}

func (a *CThostFtdcTraderApi) ReqQryParkedOrderAction(pQryParkedOrderAction *CThostFtdcQryParkedOrderActionField, nRequestID int) int {
	cpQryParkedOrderAction := CThostFtdcQryParkedOrderActionFieldCValue(pQryParkedOrderAction)
	defer func() {
		C.free(unsafe.Pointer(cpQryParkedOrderAction))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_qry_parked_order_action(a.p, cpQryParkedOrderAction, cnRequestID)

	return int(ret)
}

func (a *CThostFtdcTraderApi) ReqQryTradingNotice(pQryTradingNotice *CThostFtdcQryTradingNoticeField, nRequestID int) int {
	cpQryTradingNotice := CThostFtdcQryTradingNoticeFieldCValue(pQryTradingNotice)
	defer func() {
		C.free(unsafe.Pointer(cpQryTradingNotice))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_qry_trading_notice(a.p, cpQryTradingNotice, cnRequestID)

	return int(ret)
}

func (a *CThostFtdcTraderApi) ReqQryBrokerTradingParams(pQryBrokerTradingParams *CThostFtdcQryBrokerTradingParamsField, nRequestID int) int {
	cpQryBrokerTradingParams := CThostFtdcQryBrokerTradingParamsFieldCValue(pQryBrokerTradingParams)
	defer func() {
		C.free(unsafe.Pointer(cpQryBrokerTradingParams))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_qry_broker_trading_params(a.p, cpQryBrokerTradingParams, cnRequestID)

	return int(ret)
}

func (a *CThostFtdcTraderApi) ReqQryBrokerTradingAlgos(pQryBrokerTradingAlgos *CThostFtdcQryBrokerTradingAlgosField, nRequestID int) int {
	cpQryBrokerTradingAlgos := CThostFtdcQryBrokerTradingAlgosFieldCValue(pQryBrokerTradingAlgos)
	defer func() {
		C.free(unsafe.Pointer(cpQryBrokerTradingAlgos))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_qry_broker_trading_algos(a.p, cpQryBrokerTradingAlgos, cnRequestID)

	return int(ret)
}

func (a *CThostFtdcTraderApi) ReqQueryCFMMCTradingAccountToken(pQueryCFMMCTradingAccountToken *CThostFtdcQueryCFMMCTradingAccountTokenField, nRequestID int) int {
	cpQueryCFMMCTradingAccountToken := CThostFtdcQueryCFMMCTradingAccountTokenFieldCValue(pQueryCFMMCTradingAccountToken)
	defer func() {
		C.free(unsafe.Pointer(cpQueryCFMMCTradingAccountToken))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_query_c_f_m_m_c_trading_account_token(a.p, cpQueryCFMMCTradingAccountToken, cnRequestID)

	return int(ret)
}

func (a *CThostFtdcTraderApi) ReqFromBankToFutureByFuture(pReqTransfer *CThostFtdcReqTransferField, nRequestID int) int {
	cpReqTransfer := CThostFtdcReqTransferFieldCValue(pReqTransfer)
	defer func() {
		C.free(unsafe.Pointer(cpReqTransfer))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_from_bank_to_future_by_future(a.p, cpReqTransfer, cnRequestID)

	return int(ret)
}

func (a *CThostFtdcTraderApi) ReqFromFutureToBankByFuture(pReqTransfer *CThostFtdcReqTransferField, nRequestID int) int {
	cpReqTransfer := CThostFtdcReqTransferFieldCValue(pReqTransfer)
	defer func() {
		C.free(unsafe.Pointer(cpReqTransfer))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_from_future_to_bank_by_future(a.p, cpReqTransfer, cnRequestID)

	return int(ret)
}

func (a *CThostFtdcTraderApi) ReqQueryBankAccountMoneyByFuture(pReqQueryAccount *CThostFtdcReqQueryAccountField, nRequestID int) int {
	cpReqQueryAccount := CThostFtdcReqQueryAccountFieldCValue(pReqQueryAccount)
	defer func() {
		C.free(unsafe.Pointer(cpReqQueryAccount))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_query_bank_account_money_by_future(a.p, cpReqQueryAccount, cnRequestID)

	return int(ret)
}

func (a *CThostFtdcTraderApi) ReqQryClassifiedInstrument(pQryClassifiedInstrument *CThostFtdcQryClassifiedInstrumentField, nRequestID int) int {
	cpQryClassifiedInstrument := CThostFtdcQryClassifiedInstrumentFieldCValue(pQryClassifiedInstrument)
	defer func() {
		C.free(unsafe.Pointer(cpQryClassifiedInstrument))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_qry_classified_instrument(a.p, cpQryClassifiedInstrument, cnRequestID)

	return int(ret)
}

func (a *CThostFtdcTraderApi) ReqQryCombPromotionParam(pQryCombPromotionParam *CThostFtdcQryCombPromotionParamField, nRequestID int) int {
	cpQryCombPromotionParam := CThostFtdcQryCombPromotionParamFieldCValue(pQryCombPromotionParam)
	defer func() {
		C.free(unsafe.Pointer(cpQryCombPromotionParam))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_qry_comb_promotion_param(a.p, cpQryCombPromotionParam, cnRequestID)

	return int(ret)
}

func (a *CThostFtdcTraderApi) ReqQryRiskSettleInvstPosition(pQryRiskSettleInvstPosition *CThostFtdcQryRiskSettleInvstPositionField, nRequestID int) int {
	cpQryRiskSettleInvstPosition := CThostFtdcQryRiskSettleInvstPositionFieldCValue(pQryRiskSettleInvstPosition)
	defer func() {
		C.free(unsafe.Pointer(cpQryRiskSettleInvstPosition))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_qry_risk_settle_invst_position(a.p, cpQryRiskSettleInvstPosition, cnRequestID)

	return int(ret)
}

func (a *CThostFtdcTraderApi) ReqQryRiskSettleProductStatus(pQryRiskSettleProductStatus *CThostFtdcQryRiskSettleProductStatusField, nRequestID int) int {
	cpQryRiskSettleProductStatus := CThostFtdcQryRiskSettleProductStatusFieldCValue(pQryRiskSettleProductStatus)
	defer func() {
		C.free(unsafe.Pointer(cpQryRiskSettleProductStatus))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_qry_risk_settle_product_status(a.p, cpQryRiskSettleProductStatus, cnRequestID)

	return int(ret)
}

func (a *CThostFtdcTraderApi) ReqQrySPBMFutureParameter(pQrySPBMFutureParameter *CThostFtdcQrySPBMFutureParameterField, nRequestID int) int {
	cpQrySPBMFutureParameter := CThostFtdcQrySPBMFutureParameterFieldCValue(pQrySPBMFutureParameter)
	defer func() {
		C.free(unsafe.Pointer(cpQrySPBMFutureParameter))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_qry_s_p_b_m_future_parameter(a.p, cpQrySPBMFutureParameter, cnRequestID)

	return int(ret)
}

func (a *CThostFtdcTraderApi) ReqQrySPBMOptionParameter(pQrySPBMOptionParameter *CThostFtdcQrySPBMOptionParameterField, nRequestID int) int {
	cpQrySPBMOptionParameter := CThostFtdcQrySPBMOptionParameterFieldCValue(pQrySPBMOptionParameter)
	defer func() {
		C.free(unsafe.Pointer(cpQrySPBMOptionParameter))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_qry_s_p_b_m_option_parameter(a.p, cpQrySPBMOptionParameter, cnRequestID)

	return int(ret)
}

func (a *CThostFtdcTraderApi) ReqQrySPBMIntraParameter(pQrySPBMIntraParameter *CThostFtdcQrySPBMIntraParameterField, nRequestID int) int {
	cpQrySPBMIntraParameter := CThostFtdcQrySPBMIntraParameterFieldCValue(pQrySPBMIntraParameter)
	defer func() {
		C.free(unsafe.Pointer(cpQrySPBMIntraParameter))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_qry_s_p_b_m_intra_parameter(a.p, cpQrySPBMIntraParameter, cnRequestID)

	return int(ret)
}

func (a *CThostFtdcTraderApi) ReqQrySPBMInterParameter(pQrySPBMInterParameter *CThostFtdcQrySPBMInterParameterField, nRequestID int) int {
	cpQrySPBMInterParameter := CThostFtdcQrySPBMInterParameterFieldCValue(pQrySPBMInterParameter)
	defer func() {
		C.free(unsafe.Pointer(cpQrySPBMInterParameter))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_qry_s_p_b_m_inter_parameter(a.p, cpQrySPBMInterParameter, cnRequestID)

	return int(ret)
}

func (a *CThostFtdcTraderApi) ReqQrySPBMPortfDefinition(pQrySPBMPortfDefinition *CThostFtdcQrySPBMPortfDefinitionField, nRequestID int) int {
	cpQrySPBMPortfDefinition := CThostFtdcQrySPBMPortfDefinitionFieldCValue(pQrySPBMPortfDefinition)
	defer func() {
		C.free(unsafe.Pointer(cpQrySPBMPortfDefinition))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_qry_s_p_b_m_portf_definition(a.p, cpQrySPBMPortfDefinition, cnRequestID)

	return int(ret)
}

func (a *CThostFtdcTraderApi) ReqQrySPBMInvestorPortfDef(pQrySPBMInvestorPortfDef *CThostFtdcQrySPBMInvestorPortfDefField, nRequestID int) int {
	cpQrySPBMInvestorPortfDef := CThostFtdcQrySPBMInvestorPortfDefFieldCValue(pQrySPBMInvestorPortfDef)
	defer func() {
		C.free(unsafe.Pointer(cpQrySPBMInvestorPortfDef))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_qry_s_p_b_m_investor_portf_def(a.p, cpQrySPBMInvestorPortfDef, cnRequestID)

	return int(ret)
}

func (a *CThostFtdcTraderApi) ReqQryInvestorPortfMarginRatio(pQryInvestorPortfMarginRatio *CThostFtdcQryInvestorPortfMarginRatioField, nRequestID int) int {
	cpQryInvestorPortfMarginRatio := CThostFtdcQryInvestorPortfMarginRatioFieldCValue(pQryInvestorPortfMarginRatio)
	defer func() {
		C.free(unsafe.Pointer(cpQryInvestorPortfMarginRatio))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_qry_investor_portf_margin_ratio(a.p, cpQryInvestorPortfMarginRatio, cnRequestID)

	return int(ret)
}

func (a *CThostFtdcTraderApi) ReqQryInvestorProdSPBMDetail(pQryInvestorProdSPBMDetail *CThostFtdcQryInvestorProdSPBMDetailField, nRequestID int) int {
	cpQryInvestorProdSPBMDetail := CThostFtdcQryInvestorProdSPBMDetailFieldCValue(pQryInvestorProdSPBMDetail)
	defer func() {
		C.free(unsafe.Pointer(cpQryInvestorProdSPBMDetail))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_qry_investor_prod_s_p_b_m_detail(a.p, cpQryInvestorProdSPBMDetail, cnRequestID)

	return int(ret)
}

func (a *CThostFtdcTraderApi) ReqQryInvestorCommoditySPMMMargin(pQryInvestorCommoditySPMMMargin *CThostFtdcQryInvestorCommoditySPMMMarginField, nRequestID int) int {
	cpQryInvestorCommoditySPMMMargin := CThostFtdcQryInvestorCommoditySPMMMarginFieldCValue(pQryInvestorCommoditySPMMMargin)
	defer func() {
		C.free(unsafe.Pointer(cpQryInvestorCommoditySPMMMargin))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_qry_investor_commodity_s_p_m_m_margin(a.p, cpQryInvestorCommoditySPMMMargin, cnRequestID)

	return int(ret)
}

func (a *CThostFtdcTraderApi) ReqQryInvestorCommodityGroupSPMMMargin(pQryInvestorCommodityGroupSPMMMargin *CThostFtdcQryInvestorCommodityGroupSPMMMarginField, nRequestID int) int {
	cpQryInvestorCommodityGroupSPMMMargin := CThostFtdcQryInvestorCommodityGroupSPMMMarginFieldCValue(pQryInvestorCommodityGroupSPMMMargin)
	defer func() {
		C.free(unsafe.Pointer(cpQryInvestorCommodityGroupSPMMMargin))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_qry_investor_commodity_group_s_p_m_m_margin(a.p, cpQryInvestorCommodityGroupSPMMMargin, cnRequestID)

	return int(ret)
}

func (a *CThostFtdcTraderApi) ReqQrySPMMInstParam(pQrySPMMInstParam *CThostFtdcQrySPMMInstParamField, nRequestID int) int {
	cpQrySPMMInstParam := CThostFtdcQrySPMMInstParamFieldCValue(pQrySPMMInstParam)
	defer func() {
		C.free(unsafe.Pointer(cpQrySPMMInstParam))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_qry_s_p_m_m_inst_param(a.p, cpQrySPMMInstParam, cnRequestID)

	return int(ret)
}

func (a *CThostFtdcTraderApi) ReqQrySPMMProductParam(pQrySPMMProductParam *CThostFtdcQrySPMMProductParamField, nRequestID int) int {
	cpQrySPMMProductParam := CThostFtdcQrySPMMProductParamFieldCValue(pQrySPMMProductParam)
	defer func() {
		C.free(unsafe.Pointer(cpQrySPMMProductParam))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_qry_s_p_m_m_product_param(a.p, cpQrySPMMProductParam, cnRequestID)

	return int(ret)
}

func (a *CThostFtdcTraderApi) ReqQrySPBMAddOnInterParameter(pQrySPBMAddOnInterParameter *CThostFtdcQrySPBMAddOnInterParameterField, nRequestID int) int {
	cpQrySPBMAddOnInterParameter := CThostFtdcQrySPBMAddOnInterParameterFieldCValue(pQrySPBMAddOnInterParameter)
	defer func() {
		C.free(unsafe.Pointer(cpQrySPBMAddOnInterParameter))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_qry_s_p_b_m_add_on_inter_parameter(a.p, cpQrySPBMAddOnInterParameter, cnRequestID)

	return int(ret)
}

func (a *CThostFtdcTraderApi) ReqQryRCAMSCombProductInfo(pQryRCAMSCombProductInfo *CThostFtdcQryRCAMSCombProductInfoField, nRequestID int) int {
	cpQryRCAMSCombProductInfo := CThostFtdcQryRCAMSCombProductInfoFieldCValue(pQryRCAMSCombProductInfo)
	defer func() {
		C.free(unsafe.Pointer(cpQryRCAMSCombProductInfo))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_qry_r_c_a_m_s_comb_product_info(a.p, cpQryRCAMSCombProductInfo, cnRequestID)

	return int(ret)
}

func (a *CThostFtdcTraderApi) ReqQryRCAMSInstrParameter(pQryRCAMSInstrParameter *CThostFtdcQryRCAMSInstrParameterField, nRequestID int) int {
	cpQryRCAMSInstrParameter := CThostFtdcQryRCAMSInstrParameterFieldCValue(pQryRCAMSInstrParameter)
	defer func() {
		C.free(unsafe.Pointer(cpQryRCAMSInstrParameter))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_qry_r_c_a_m_s_instr_parameter(a.p, cpQryRCAMSInstrParameter, cnRequestID)

	return int(ret)
}

func (a *CThostFtdcTraderApi) ReqQryRCAMSIntraParameter(pQryRCAMSIntraParameter *CThostFtdcQryRCAMSIntraParameterField, nRequestID int) int {
	cpQryRCAMSIntraParameter := CThostFtdcQryRCAMSIntraParameterFieldCValue(pQryRCAMSIntraParameter)
	defer func() {
		C.free(unsafe.Pointer(cpQryRCAMSIntraParameter))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_qry_r_c_a_m_s_intra_parameter(a.p, cpQryRCAMSIntraParameter, cnRequestID)

	return int(ret)
}

func (a *CThostFtdcTraderApi) ReqQryRCAMSInterParameter(pQryRCAMSInterParameter *CThostFtdcQryRCAMSInterParameterField, nRequestID int) int {
	cpQryRCAMSInterParameter := CThostFtdcQryRCAMSInterParameterFieldCValue(pQryRCAMSInterParameter)
	defer func() {
		C.free(unsafe.Pointer(cpQryRCAMSInterParameter))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_qry_r_c_a_m_s_inter_parameter(a.p, cpQryRCAMSInterParameter, cnRequestID)

	return int(ret)
}

func (a *CThostFtdcTraderApi) ReqQryRCAMSShortOptAdjustParam(pQryRCAMSShortOptAdjustParam *CThostFtdcQryRCAMSShortOptAdjustParamField, nRequestID int) int {
	cpQryRCAMSShortOptAdjustParam := CThostFtdcQryRCAMSShortOptAdjustParamFieldCValue(pQryRCAMSShortOptAdjustParam)
	defer func() {
		C.free(unsafe.Pointer(cpQryRCAMSShortOptAdjustParam))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_qry_r_c_a_m_s_short_opt_adjust_param(a.p, cpQryRCAMSShortOptAdjustParam, cnRequestID)

	return int(ret)
}

func (a *CThostFtdcTraderApi) ReqQryRCAMSInvestorCombPosition(pQryRCAMSInvestorCombPosition *CThostFtdcQryRCAMSInvestorCombPositionField, nRequestID int) int {
	cpQryRCAMSInvestorCombPosition := CThostFtdcQryRCAMSInvestorCombPositionFieldCValue(pQryRCAMSInvestorCombPosition)
	defer func() {
		C.free(unsafe.Pointer(cpQryRCAMSInvestorCombPosition))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_qry_r_c_a_m_s_investor_comb_position(a.p, cpQryRCAMSInvestorCombPosition, cnRequestID)

	return int(ret)
}

func (a *CThostFtdcTraderApi) ReqQryInvestorProdRCAMSMargin(pQryInvestorProdRCAMSMargin *CThostFtdcQryInvestorProdRCAMSMarginField, nRequestID int) int {
	cpQryInvestorProdRCAMSMargin := CThostFtdcQryInvestorProdRCAMSMarginFieldCValue(pQryInvestorProdRCAMSMargin)
	defer func() {
		C.free(unsafe.Pointer(cpQryInvestorProdRCAMSMargin))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_qry_investor_prod_r_c_a_m_s_margin(a.p, cpQryInvestorProdRCAMSMargin, cnRequestID)

	return int(ret)
}

func (a *CThostFtdcTraderApi) ReqQryRULEInstrParameter(pQryRULEInstrParameter *CThostFtdcQryRULEInstrParameterField, nRequestID int) int {
	cpQryRULEInstrParameter := CThostFtdcQryRULEInstrParameterFieldCValue(pQryRULEInstrParameter)
	defer func() {
		C.free(unsafe.Pointer(cpQryRULEInstrParameter))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_qry_r_u_l_e_instr_parameter(a.p, cpQryRULEInstrParameter, cnRequestID)

	return int(ret)
}

func (a *CThostFtdcTraderApi) ReqQryRULEIntraParameter(pQryRULEIntraParameter *CThostFtdcQryRULEIntraParameterField, nRequestID int) int {
	cpQryRULEIntraParameter := CThostFtdcQryRULEIntraParameterFieldCValue(pQryRULEIntraParameter)
	defer func() {
		C.free(unsafe.Pointer(cpQryRULEIntraParameter))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_qry_r_u_l_e_intra_parameter(a.p, cpQryRULEIntraParameter, cnRequestID)

	return int(ret)
}

func (a *CThostFtdcTraderApi) ReqQryRULEInterParameter(pQryRULEInterParameter *CThostFtdcQryRULEInterParameterField, nRequestID int) int {
	cpQryRULEInterParameter := CThostFtdcQryRULEInterParameterFieldCValue(pQryRULEInterParameter)
	defer func() {
		C.free(unsafe.Pointer(cpQryRULEInterParameter))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_qry_r_u_l_e_inter_parameter(a.p, cpQryRULEInterParameter, cnRequestID)

	return int(ret)
}

func (a *CThostFtdcTraderApi) ReqQryInvestorProdRULEMargin(pQryInvestorProdRULEMargin *CThostFtdcQryInvestorProdRULEMarginField, nRequestID int) int {
	cpQryInvestorProdRULEMargin := CThostFtdcQryInvestorProdRULEMarginFieldCValue(pQryInvestorProdRULEMargin)
	defer func() {
		C.free(unsafe.Pointer(cpQryInvestorProdRULEMargin))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_qry_investor_prod_r_u_l_e_margin(a.p, cpQryInvestorProdRULEMargin, cnRequestID)

	return int(ret)
}

func (a *CThostFtdcTraderApi) ReqQryInvestorPortfSetting(pQryInvestorPortfSetting *CThostFtdcQryInvestorPortfSettingField, nRequestID int) int {
	cpQryInvestorPortfSetting := CThostFtdcQryInvestorPortfSettingFieldCValue(pQryInvestorPortfSetting)
	defer func() {
		C.free(unsafe.Pointer(cpQryInvestorPortfSetting))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_qry_investor_portf_setting(a.p, cpQryInvestorPortfSetting, cnRequestID)

	return int(ret)
}

func (a *CThostFtdcTraderApi) ReqQryInvestorInfoCommRec(pQryInvestorInfoCommRec *CThostFtdcQryInvestorInfoCommRecField, nRequestID int) int {
	cpQryInvestorInfoCommRec := CThostFtdcQryInvestorInfoCommRecFieldCValue(pQryInvestorInfoCommRec)
	defer func() {
		C.free(unsafe.Pointer(cpQryInvestorInfoCommRec))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_qry_investor_info_comm_rec(a.p, cpQryInvestorInfoCommRec, cnRequestID)

	return int(ret)
}

func (a *CThostFtdcTraderApi) ReqQryCombLeg(pQryCombLeg *CThostFtdcQryCombLegField, nRequestID int) int {
	cpQryCombLeg := CThostFtdcQryCombLegFieldCValue(pQryCombLeg)
	defer func() {
		C.free(unsafe.Pointer(cpQryCombLeg))
	}()
	cnRequestID := C.int(nRequestID)

	ret := C.td_req_qry_comb_leg(a.p, cpQryCombLeg, cnRequestID)

	return int(ret)
}
