#ifndef _CTP_TYPES_GEN_H
#define _CTP_TYPES_GEN_H
#include "include/ThostFtdcUserApiStruct.h"
typedef struct CThostFtdcDisseminationField CThostFtdcDisseminationField;
CThostFtdcDisseminationField* newCThostFtdcDisseminationField();

typedef struct CThostFtdcReqUserLoginField CThostFtdcReqUserLoginField;
CThostFtdcReqUserLoginField* newCThostFtdcReqUserLoginField();

typedef struct CThostFtdcRspUserLoginField CThostFtdcRspUserLoginField;
CThostFtdcRspUserLoginField* newCThostFtdcRspUserLoginField();

typedef struct CThostFtdcUserLogoutField CThostFtdcUserLogoutField;
CThostFtdcUserLogoutField* newCThostFtdcUserLogoutField();

typedef struct CThostFtdcForceUserLogoutField CThostFtdcForceUserLogoutField;
CThostFtdcForceUserLogoutField* newCThostFtdcForceUserLogoutField();

typedef struct CThostFtdcReqAuthenticateField CThostFtdcReqAuthenticateField;
CThostFtdcReqAuthenticateField* newCThostFtdcReqAuthenticateField();

typedef struct CThostFtdcRspAuthenticateField CThostFtdcRspAuthenticateField;
CThostFtdcRspAuthenticateField* newCThostFtdcRspAuthenticateField();

typedef struct CThostFtdcAuthenticationInfoField CThostFtdcAuthenticationInfoField;
CThostFtdcAuthenticationInfoField* newCThostFtdcAuthenticationInfoField();

typedef struct CThostFtdcRspUserLogin2Field CThostFtdcRspUserLogin2Field;
CThostFtdcRspUserLogin2Field* newCThostFtdcRspUserLogin2Field();

typedef struct CThostFtdcTransferHeaderField CThostFtdcTransferHeaderField;
CThostFtdcTransferHeaderField* newCThostFtdcTransferHeaderField();

typedef struct CThostFtdcTransferBankToFutureReqField CThostFtdcTransferBankToFutureReqField;
CThostFtdcTransferBankToFutureReqField* newCThostFtdcTransferBankToFutureReqField();

typedef struct CThostFtdcTransferBankToFutureRspField CThostFtdcTransferBankToFutureRspField;
CThostFtdcTransferBankToFutureRspField* newCThostFtdcTransferBankToFutureRspField();

typedef struct CThostFtdcTransferFutureToBankReqField CThostFtdcTransferFutureToBankReqField;
CThostFtdcTransferFutureToBankReqField* newCThostFtdcTransferFutureToBankReqField();

typedef struct CThostFtdcTransferFutureToBankRspField CThostFtdcTransferFutureToBankRspField;
CThostFtdcTransferFutureToBankRspField* newCThostFtdcTransferFutureToBankRspField();

typedef struct CThostFtdcTransferQryBankReqField CThostFtdcTransferQryBankReqField;
CThostFtdcTransferQryBankReqField* newCThostFtdcTransferQryBankReqField();

typedef struct CThostFtdcTransferQryBankRspField CThostFtdcTransferQryBankRspField;
CThostFtdcTransferQryBankRspField* newCThostFtdcTransferQryBankRspField();

typedef struct CThostFtdcTransferQryDetailReqField CThostFtdcTransferQryDetailReqField;
CThostFtdcTransferQryDetailReqField* newCThostFtdcTransferQryDetailReqField();

typedef struct CThostFtdcTransferQryDetailRspField CThostFtdcTransferQryDetailRspField;
CThostFtdcTransferQryDetailRspField* newCThostFtdcTransferQryDetailRspField();

typedef struct CThostFtdcRspInfoField CThostFtdcRspInfoField;
CThostFtdcRspInfoField* newCThostFtdcRspInfoField();

typedef struct CThostFtdcExchangeField CThostFtdcExchangeField;
CThostFtdcExchangeField* newCThostFtdcExchangeField();

typedef struct CThostFtdcProductField CThostFtdcProductField;
CThostFtdcProductField* newCThostFtdcProductField();

typedef struct CThostFtdcInstrumentField CThostFtdcInstrumentField;
CThostFtdcInstrumentField* newCThostFtdcInstrumentField();

typedef struct CThostFtdcBrokerField CThostFtdcBrokerField;
CThostFtdcBrokerField* newCThostFtdcBrokerField();

typedef struct CThostFtdcTraderField CThostFtdcTraderField;
CThostFtdcTraderField* newCThostFtdcTraderField();

typedef struct CThostFtdcInvestorField CThostFtdcInvestorField;
CThostFtdcInvestorField* newCThostFtdcInvestorField();

typedef struct CThostFtdcTradingCodeField CThostFtdcTradingCodeField;
CThostFtdcTradingCodeField* newCThostFtdcTradingCodeField();

typedef struct CThostFtdcPartBrokerField CThostFtdcPartBrokerField;
CThostFtdcPartBrokerField* newCThostFtdcPartBrokerField();

typedef struct CThostFtdcSuperUserField CThostFtdcSuperUserField;
CThostFtdcSuperUserField* newCThostFtdcSuperUserField();

typedef struct CThostFtdcSuperUserFunctionField CThostFtdcSuperUserFunctionField;
CThostFtdcSuperUserFunctionField* newCThostFtdcSuperUserFunctionField();

typedef struct CThostFtdcInvestorGroupField CThostFtdcInvestorGroupField;
CThostFtdcInvestorGroupField* newCThostFtdcInvestorGroupField();

typedef struct CThostFtdcTradingAccountField CThostFtdcTradingAccountField;
CThostFtdcTradingAccountField* newCThostFtdcTradingAccountField();

typedef struct CThostFtdcInvestorPositionField CThostFtdcInvestorPositionField;
CThostFtdcInvestorPositionField* newCThostFtdcInvestorPositionField();

typedef struct CThostFtdcInstrumentMarginRateField CThostFtdcInstrumentMarginRateField;
CThostFtdcInstrumentMarginRateField* newCThostFtdcInstrumentMarginRateField();

typedef struct CThostFtdcInstrumentCommissionRateField CThostFtdcInstrumentCommissionRateField;
CThostFtdcInstrumentCommissionRateField* newCThostFtdcInstrumentCommissionRateField();

typedef struct CThostFtdcDepthMarketDataField CThostFtdcDepthMarketDataField;
CThostFtdcDepthMarketDataField* newCThostFtdcDepthMarketDataField();

typedef struct CThostFtdcInstrumentTradingRightField CThostFtdcInstrumentTradingRightField;
CThostFtdcInstrumentTradingRightField* newCThostFtdcInstrumentTradingRightField();

typedef struct CThostFtdcBrokerUserField CThostFtdcBrokerUserField;
CThostFtdcBrokerUserField* newCThostFtdcBrokerUserField();

typedef struct CThostFtdcBrokerUserPasswordField CThostFtdcBrokerUserPasswordField;
CThostFtdcBrokerUserPasswordField* newCThostFtdcBrokerUserPasswordField();

typedef struct CThostFtdcBrokerUserFunctionField CThostFtdcBrokerUserFunctionField;
CThostFtdcBrokerUserFunctionField* newCThostFtdcBrokerUserFunctionField();

typedef struct CThostFtdcTraderOfferField CThostFtdcTraderOfferField;
CThostFtdcTraderOfferField* newCThostFtdcTraderOfferField();

typedef struct CThostFtdcSettlementInfoField CThostFtdcSettlementInfoField;
CThostFtdcSettlementInfoField* newCThostFtdcSettlementInfoField();

typedef struct CThostFtdcInstrumentMarginRateAdjustField CThostFtdcInstrumentMarginRateAdjustField;
CThostFtdcInstrumentMarginRateAdjustField* newCThostFtdcInstrumentMarginRateAdjustField();

typedef struct CThostFtdcExchangeMarginRateField CThostFtdcExchangeMarginRateField;
CThostFtdcExchangeMarginRateField* newCThostFtdcExchangeMarginRateField();

typedef struct CThostFtdcExchangeMarginRateAdjustField CThostFtdcExchangeMarginRateAdjustField;
CThostFtdcExchangeMarginRateAdjustField* newCThostFtdcExchangeMarginRateAdjustField();

typedef struct CThostFtdcExchangeRateField CThostFtdcExchangeRateField;
CThostFtdcExchangeRateField* newCThostFtdcExchangeRateField();

typedef struct CThostFtdcSettlementRefField CThostFtdcSettlementRefField;
CThostFtdcSettlementRefField* newCThostFtdcSettlementRefField();

typedef struct CThostFtdcCurrentTimeField CThostFtdcCurrentTimeField;
CThostFtdcCurrentTimeField* newCThostFtdcCurrentTimeField();

typedef struct CThostFtdcCommPhaseField CThostFtdcCommPhaseField;
CThostFtdcCommPhaseField* newCThostFtdcCommPhaseField();

typedef struct CThostFtdcLoginInfoField CThostFtdcLoginInfoField;
CThostFtdcLoginInfoField* newCThostFtdcLoginInfoField();

typedef struct CThostFtdcLogoutAllField CThostFtdcLogoutAllField;
CThostFtdcLogoutAllField* newCThostFtdcLogoutAllField();

typedef struct CThostFtdcFrontStatusField CThostFtdcFrontStatusField;
CThostFtdcFrontStatusField* newCThostFtdcFrontStatusField();

typedef struct CThostFtdcUserPasswordUpdateField CThostFtdcUserPasswordUpdateField;
CThostFtdcUserPasswordUpdateField* newCThostFtdcUserPasswordUpdateField();

typedef struct CThostFtdcInputOrderField CThostFtdcInputOrderField;
CThostFtdcInputOrderField* newCThostFtdcInputOrderField();

typedef struct CThostFtdcOrderField CThostFtdcOrderField;
CThostFtdcOrderField* newCThostFtdcOrderField();

typedef struct CThostFtdcExchangeOrderField CThostFtdcExchangeOrderField;
CThostFtdcExchangeOrderField* newCThostFtdcExchangeOrderField();

typedef struct CThostFtdcExchangeOrderInsertErrorField CThostFtdcExchangeOrderInsertErrorField;
CThostFtdcExchangeOrderInsertErrorField* newCThostFtdcExchangeOrderInsertErrorField();

typedef struct CThostFtdcInputOrderActionField CThostFtdcInputOrderActionField;
CThostFtdcInputOrderActionField* newCThostFtdcInputOrderActionField();

typedef struct CThostFtdcOrderActionField CThostFtdcOrderActionField;
CThostFtdcOrderActionField* newCThostFtdcOrderActionField();

typedef struct CThostFtdcExchangeOrderActionField CThostFtdcExchangeOrderActionField;
CThostFtdcExchangeOrderActionField* newCThostFtdcExchangeOrderActionField();

typedef struct CThostFtdcExchangeOrderActionErrorField CThostFtdcExchangeOrderActionErrorField;
CThostFtdcExchangeOrderActionErrorField* newCThostFtdcExchangeOrderActionErrorField();

typedef struct CThostFtdcExchangeTradeField CThostFtdcExchangeTradeField;
CThostFtdcExchangeTradeField* newCThostFtdcExchangeTradeField();

typedef struct CThostFtdcTradeField CThostFtdcTradeField;
CThostFtdcTradeField* newCThostFtdcTradeField();

typedef struct CThostFtdcUserSessionField CThostFtdcUserSessionField;
CThostFtdcUserSessionField* newCThostFtdcUserSessionField();

typedef struct CThostFtdcQueryMaxOrderVolumeField CThostFtdcQueryMaxOrderVolumeField;
CThostFtdcQueryMaxOrderVolumeField* newCThostFtdcQueryMaxOrderVolumeField();

typedef struct CThostFtdcSettlementInfoConfirmField CThostFtdcSettlementInfoConfirmField;
CThostFtdcSettlementInfoConfirmField* newCThostFtdcSettlementInfoConfirmField();

typedef struct CThostFtdcSyncDepositField CThostFtdcSyncDepositField;
CThostFtdcSyncDepositField* newCThostFtdcSyncDepositField();

typedef struct CThostFtdcSyncFundMortgageField CThostFtdcSyncFundMortgageField;
CThostFtdcSyncFundMortgageField* newCThostFtdcSyncFundMortgageField();

typedef struct CThostFtdcBrokerSyncField CThostFtdcBrokerSyncField;
CThostFtdcBrokerSyncField* newCThostFtdcBrokerSyncField();

typedef struct CThostFtdcSyncingInvestorField CThostFtdcSyncingInvestorField;
CThostFtdcSyncingInvestorField* newCThostFtdcSyncingInvestorField();

typedef struct CThostFtdcSyncingTradingCodeField CThostFtdcSyncingTradingCodeField;
CThostFtdcSyncingTradingCodeField* newCThostFtdcSyncingTradingCodeField();

typedef struct CThostFtdcSyncingInvestorGroupField CThostFtdcSyncingInvestorGroupField;
CThostFtdcSyncingInvestorGroupField* newCThostFtdcSyncingInvestorGroupField();

typedef struct CThostFtdcSyncingTradingAccountField CThostFtdcSyncingTradingAccountField;
CThostFtdcSyncingTradingAccountField* newCThostFtdcSyncingTradingAccountField();

typedef struct CThostFtdcSyncingInvestorPositionField CThostFtdcSyncingInvestorPositionField;
CThostFtdcSyncingInvestorPositionField* newCThostFtdcSyncingInvestorPositionField();

typedef struct CThostFtdcSyncingInstrumentMarginRateField CThostFtdcSyncingInstrumentMarginRateField;
CThostFtdcSyncingInstrumentMarginRateField* newCThostFtdcSyncingInstrumentMarginRateField();

typedef struct CThostFtdcSyncingInstrumentCommissionRateField CThostFtdcSyncingInstrumentCommissionRateField;
CThostFtdcSyncingInstrumentCommissionRateField* newCThostFtdcSyncingInstrumentCommissionRateField();

typedef struct CThostFtdcSyncingInstrumentTradingRightField CThostFtdcSyncingInstrumentTradingRightField;
CThostFtdcSyncingInstrumentTradingRightField* newCThostFtdcSyncingInstrumentTradingRightField();

typedef struct CThostFtdcQryOrderField CThostFtdcQryOrderField;
CThostFtdcQryOrderField* newCThostFtdcQryOrderField();

typedef struct CThostFtdcQryTradeField CThostFtdcQryTradeField;
CThostFtdcQryTradeField* newCThostFtdcQryTradeField();

typedef struct CThostFtdcQryInvestorPositionField CThostFtdcQryInvestorPositionField;
CThostFtdcQryInvestorPositionField* newCThostFtdcQryInvestorPositionField();

typedef struct CThostFtdcQryTradingAccountField CThostFtdcQryTradingAccountField;
CThostFtdcQryTradingAccountField* newCThostFtdcQryTradingAccountField();

typedef struct CThostFtdcQryInvestorField CThostFtdcQryInvestorField;
CThostFtdcQryInvestorField* newCThostFtdcQryInvestorField();

typedef struct CThostFtdcQryTradingCodeField CThostFtdcQryTradingCodeField;
CThostFtdcQryTradingCodeField* newCThostFtdcQryTradingCodeField();

typedef struct CThostFtdcQryInvestorGroupField CThostFtdcQryInvestorGroupField;
CThostFtdcQryInvestorGroupField* newCThostFtdcQryInvestorGroupField();

typedef struct CThostFtdcQryInstrumentMarginRateField CThostFtdcQryInstrumentMarginRateField;
CThostFtdcQryInstrumentMarginRateField* newCThostFtdcQryInstrumentMarginRateField();

typedef struct CThostFtdcQryInstrumentCommissionRateField CThostFtdcQryInstrumentCommissionRateField;
CThostFtdcQryInstrumentCommissionRateField* newCThostFtdcQryInstrumentCommissionRateField();

typedef struct CThostFtdcQryInstrumentTradingRightField CThostFtdcQryInstrumentTradingRightField;
CThostFtdcQryInstrumentTradingRightField* newCThostFtdcQryInstrumentTradingRightField();

typedef struct CThostFtdcQryBrokerField CThostFtdcQryBrokerField;
CThostFtdcQryBrokerField* newCThostFtdcQryBrokerField();

typedef struct CThostFtdcQryTraderField CThostFtdcQryTraderField;
CThostFtdcQryTraderField* newCThostFtdcQryTraderField();

typedef struct CThostFtdcQrySuperUserFunctionField CThostFtdcQrySuperUserFunctionField;
CThostFtdcQrySuperUserFunctionField* newCThostFtdcQrySuperUserFunctionField();

typedef struct CThostFtdcQryUserSessionField CThostFtdcQryUserSessionField;
CThostFtdcQryUserSessionField* newCThostFtdcQryUserSessionField();

typedef struct CThostFtdcQryPartBrokerField CThostFtdcQryPartBrokerField;
CThostFtdcQryPartBrokerField* newCThostFtdcQryPartBrokerField();

typedef struct CThostFtdcQryFrontStatusField CThostFtdcQryFrontStatusField;
CThostFtdcQryFrontStatusField* newCThostFtdcQryFrontStatusField();

typedef struct CThostFtdcQryExchangeOrderField CThostFtdcQryExchangeOrderField;
CThostFtdcQryExchangeOrderField* newCThostFtdcQryExchangeOrderField();

typedef struct CThostFtdcQryOrderActionField CThostFtdcQryOrderActionField;
CThostFtdcQryOrderActionField* newCThostFtdcQryOrderActionField();

typedef struct CThostFtdcQryExchangeOrderActionField CThostFtdcQryExchangeOrderActionField;
CThostFtdcQryExchangeOrderActionField* newCThostFtdcQryExchangeOrderActionField();

typedef struct CThostFtdcQrySuperUserField CThostFtdcQrySuperUserField;
CThostFtdcQrySuperUserField* newCThostFtdcQrySuperUserField();

typedef struct CThostFtdcQryExchangeField CThostFtdcQryExchangeField;
CThostFtdcQryExchangeField* newCThostFtdcQryExchangeField();

typedef struct CThostFtdcQryProductField CThostFtdcQryProductField;
CThostFtdcQryProductField* newCThostFtdcQryProductField();

typedef struct CThostFtdcQryInstrumentField CThostFtdcQryInstrumentField;
CThostFtdcQryInstrumentField* newCThostFtdcQryInstrumentField();

typedef struct CThostFtdcQryDepthMarketDataField CThostFtdcQryDepthMarketDataField;
CThostFtdcQryDepthMarketDataField* newCThostFtdcQryDepthMarketDataField();

typedef struct CThostFtdcQryBrokerUserField CThostFtdcQryBrokerUserField;
CThostFtdcQryBrokerUserField* newCThostFtdcQryBrokerUserField();

typedef struct CThostFtdcQryBrokerUserFunctionField CThostFtdcQryBrokerUserFunctionField;
CThostFtdcQryBrokerUserFunctionField* newCThostFtdcQryBrokerUserFunctionField();

typedef struct CThostFtdcQryTraderOfferField CThostFtdcQryTraderOfferField;
CThostFtdcQryTraderOfferField* newCThostFtdcQryTraderOfferField();

typedef struct CThostFtdcQrySyncDepositField CThostFtdcQrySyncDepositField;
CThostFtdcQrySyncDepositField* newCThostFtdcQrySyncDepositField();

typedef struct CThostFtdcQrySettlementInfoField CThostFtdcQrySettlementInfoField;
CThostFtdcQrySettlementInfoField* newCThostFtdcQrySettlementInfoField();

typedef struct CThostFtdcQryExchangeMarginRateField CThostFtdcQryExchangeMarginRateField;
CThostFtdcQryExchangeMarginRateField* newCThostFtdcQryExchangeMarginRateField();

typedef struct CThostFtdcQryExchangeMarginRateAdjustField CThostFtdcQryExchangeMarginRateAdjustField;
CThostFtdcQryExchangeMarginRateAdjustField* newCThostFtdcQryExchangeMarginRateAdjustField();

typedef struct CThostFtdcQryExchangeRateField CThostFtdcQryExchangeRateField;
CThostFtdcQryExchangeRateField* newCThostFtdcQryExchangeRateField();

typedef struct CThostFtdcQrySyncFundMortgageField CThostFtdcQrySyncFundMortgageField;
CThostFtdcQrySyncFundMortgageField* newCThostFtdcQrySyncFundMortgageField();

typedef struct CThostFtdcQryHisOrderField CThostFtdcQryHisOrderField;
CThostFtdcQryHisOrderField* newCThostFtdcQryHisOrderField();

typedef struct CThostFtdcOptionInstrMiniMarginField CThostFtdcOptionInstrMiniMarginField;
CThostFtdcOptionInstrMiniMarginField* newCThostFtdcOptionInstrMiniMarginField();

typedef struct CThostFtdcOptionInstrMarginAdjustField CThostFtdcOptionInstrMarginAdjustField;
CThostFtdcOptionInstrMarginAdjustField* newCThostFtdcOptionInstrMarginAdjustField();

typedef struct CThostFtdcOptionInstrCommRateField CThostFtdcOptionInstrCommRateField;
CThostFtdcOptionInstrCommRateField* newCThostFtdcOptionInstrCommRateField();

typedef struct CThostFtdcOptionInstrTradeCostField CThostFtdcOptionInstrTradeCostField;
CThostFtdcOptionInstrTradeCostField* newCThostFtdcOptionInstrTradeCostField();

typedef struct CThostFtdcQryOptionInstrTradeCostField CThostFtdcQryOptionInstrTradeCostField;
CThostFtdcQryOptionInstrTradeCostField* newCThostFtdcQryOptionInstrTradeCostField();

typedef struct CThostFtdcQryOptionInstrCommRateField CThostFtdcQryOptionInstrCommRateField;
CThostFtdcQryOptionInstrCommRateField* newCThostFtdcQryOptionInstrCommRateField();

typedef struct CThostFtdcIndexPriceField CThostFtdcIndexPriceField;
CThostFtdcIndexPriceField* newCThostFtdcIndexPriceField();

typedef struct CThostFtdcInputExecOrderField CThostFtdcInputExecOrderField;
CThostFtdcInputExecOrderField* newCThostFtdcInputExecOrderField();

typedef struct CThostFtdcInputExecOrderActionField CThostFtdcInputExecOrderActionField;
CThostFtdcInputExecOrderActionField* newCThostFtdcInputExecOrderActionField();

typedef struct CThostFtdcExecOrderField CThostFtdcExecOrderField;
CThostFtdcExecOrderField* newCThostFtdcExecOrderField();

typedef struct CThostFtdcExecOrderActionField CThostFtdcExecOrderActionField;
CThostFtdcExecOrderActionField* newCThostFtdcExecOrderActionField();

typedef struct CThostFtdcQryExecOrderField CThostFtdcQryExecOrderField;
CThostFtdcQryExecOrderField* newCThostFtdcQryExecOrderField();

typedef struct CThostFtdcExchangeExecOrderField CThostFtdcExchangeExecOrderField;
CThostFtdcExchangeExecOrderField* newCThostFtdcExchangeExecOrderField();

typedef struct CThostFtdcQryExchangeExecOrderField CThostFtdcQryExchangeExecOrderField;
CThostFtdcQryExchangeExecOrderField* newCThostFtdcQryExchangeExecOrderField();

typedef struct CThostFtdcQryExecOrderActionField CThostFtdcQryExecOrderActionField;
CThostFtdcQryExecOrderActionField* newCThostFtdcQryExecOrderActionField();

typedef struct CThostFtdcExchangeExecOrderActionField CThostFtdcExchangeExecOrderActionField;
CThostFtdcExchangeExecOrderActionField* newCThostFtdcExchangeExecOrderActionField();

typedef struct CThostFtdcQryExchangeExecOrderActionField CThostFtdcQryExchangeExecOrderActionField;
CThostFtdcQryExchangeExecOrderActionField* newCThostFtdcQryExchangeExecOrderActionField();

typedef struct CThostFtdcErrExecOrderField CThostFtdcErrExecOrderField;
CThostFtdcErrExecOrderField* newCThostFtdcErrExecOrderField();

typedef struct CThostFtdcQryErrExecOrderField CThostFtdcQryErrExecOrderField;
CThostFtdcQryErrExecOrderField* newCThostFtdcQryErrExecOrderField();

typedef struct CThostFtdcErrExecOrderActionField CThostFtdcErrExecOrderActionField;
CThostFtdcErrExecOrderActionField* newCThostFtdcErrExecOrderActionField();

typedef struct CThostFtdcQryErrExecOrderActionField CThostFtdcQryErrExecOrderActionField;
CThostFtdcQryErrExecOrderActionField* newCThostFtdcQryErrExecOrderActionField();

typedef struct CThostFtdcOptionInstrTradingRightField CThostFtdcOptionInstrTradingRightField;
CThostFtdcOptionInstrTradingRightField* newCThostFtdcOptionInstrTradingRightField();

typedef struct CThostFtdcQryOptionInstrTradingRightField CThostFtdcQryOptionInstrTradingRightField;
CThostFtdcQryOptionInstrTradingRightField* newCThostFtdcQryOptionInstrTradingRightField();

typedef struct CThostFtdcInputForQuoteField CThostFtdcInputForQuoteField;
CThostFtdcInputForQuoteField* newCThostFtdcInputForQuoteField();

typedef struct CThostFtdcForQuoteField CThostFtdcForQuoteField;
CThostFtdcForQuoteField* newCThostFtdcForQuoteField();

typedef struct CThostFtdcQryForQuoteField CThostFtdcQryForQuoteField;
CThostFtdcQryForQuoteField* newCThostFtdcQryForQuoteField();

typedef struct CThostFtdcExchangeForQuoteField CThostFtdcExchangeForQuoteField;
CThostFtdcExchangeForQuoteField* newCThostFtdcExchangeForQuoteField();

typedef struct CThostFtdcQryExchangeForQuoteField CThostFtdcQryExchangeForQuoteField;
CThostFtdcQryExchangeForQuoteField* newCThostFtdcQryExchangeForQuoteField();

typedef struct CThostFtdcInputQuoteField CThostFtdcInputQuoteField;
CThostFtdcInputQuoteField* newCThostFtdcInputQuoteField();

typedef struct CThostFtdcInputQuoteActionField CThostFtdcInputQuoteActionField;
CThostFtdcInputQuoteActionField* newCThostFtdcInputQuoteActionField();

typedef struct CThostFtdcQuoteField CThostFtdcQuoteField;
CThostFtdcQuoteField* newCThostFtdcQuoteField();

typedef struct CThostFtdcQuoteActionField CThostFtdcQuoteActionField;
CThostFtdcQuoteActionField* newCThostFtdcQuoteActionField();

typedef struct CThostFtdcQryQuoteField CThostFtdcQryQuoteField;
CThostFtdcQryQuoteField* newCThostFtdcQryQuoteField();

typedef struct CThostFtdcExchangeQuoteField CThostFtdcExchangeQuoteField;
CThostFtdcExchangeQuoteField* newCThostFtdcExchangeQuoteField();

typedef struct CThostFtdcQryExchangeQuoteField CThostFtdcQryExchangeQuoteField;
CThostFtdcQryExchangeQuoteField* newCThostFtdcQryExchangeQuoteField();

typedef struct CThostFtdcQryQuoteActionField CThostFtdcQryQuoteActionField;
CThostFtdcQryQuoteActionField* newCThostFtdcQryQuoteActionField();

typedef struct CThostFtdcExchangeQuoteActionField CThostFtdcExchangeQuoteActionField;
CThostFtdcExchangeQuoteActionField* newCThostFtdcExchangeQuoteActionField();

typedef struct CThostFtdcQryExchangeQuoteActionField CThostFtdcQryExchangeQuoteActionField;
CThostFtdcQryExchangeQuoteActionField* newCThostFtdcQryExchangeQuoteActionField();

typedef struct CThostFtdcOptionInstrDeltaField CThostFtdcOptionInstrDeltaField;
CThostFtdcOptionInstrDeltaField* newCThostFtdcOptionInstrDeltaField();

typedef struct CThostFtdcForQuoteRspField CThostFtdcForQuoteRspField;
CThostFtdcForQuoteRspField* newCThostFtdcForQuoteRspField();

typedef struct CThostFtdcStrikeOffsetField CThostFtdcStrikeOffsetField;
CThostFtdcStrikeOffsetField* newCThostFtdcStrikeOffsetField();

typedef struct CThostFtdcQryStrikeOffsetField CThostFtdcQryStrikeOffsetField;
CThostFtdcQryStrikeOffsetField* newCThostFtdcQryStrikeOffsetField();

typedef struct CThostFtdcInputBatchOrderActionField CThostFtdcInputBatchOrderActionField;
CThostFtdcInputBatchOrderActionField* newCThostFtdcInputBatchOrderActionField();

typedef struct CThostFtdcBatchOrderActionField CThostFtdcBatchOrderActionField;
CThostFtdcBatchOrderActionField* newCThostFtdcBatchOrderActionField();

typedef struct CThostFtdcExchangeBatchOrderActionField CThostFtdcExchangeBatchOrderActionField;
CThostFtdcExchangeBatchOrderActionField* newCThostFtdcExchangeBatchOrderActionField();

typedef struct CThostFtdcQryBatchOrderActionField CThostFtdcQryBatchOrderActionField;
CThostFtdcQryBatchOrderActionField* newCThostFtdcQryBatchOrderActionField();

typedef struct CThostFtdcCombInstrumentGuardField CThostFtdcCombInstrumentGuardField;
CThostFtdcCombInstrumentGuardField* newCThostFtdcCombInstrumentGuardField();

typedef struct CThostFtdcQryCombInstrumentGuardField CThostFtdcQryCombInstrumentGuardField;
CThostFtdcQryCombInstrumentGuardField* newCThostFtdcQryCombInstrumentGuardField();

typedef struct CThostFtdcInputCombActionField CThostFtdcInputCombActionField;
CThostFtdcInputCombActionField* newCThostFtdcInputCombActionField();

typedef struct CThostFtdcCombActionField CThostFtdcCombActionField;
CThostFtdcCombActionField* newCThostFtdcCombActionField();

typedef struct CThostFtdcQryCombActionField CThostFtdcQryCombActionField;
CThostFtdcQryCombActionField* newCThostFtdcQryCombActionField();

typedef struct CThostFtdcExchangeCombActionField CThostFtdcExchangeCombActionField;
CThostFtdcExchangeCombActionField* newCThostFtdcExchangeCombActionField();

typedef struct CThostFtdcQryExchangeCombActionField CThostFtdcQryExchangeCombActionField;
CThostFtdcQryExchangeCombActionField* newCThostFtdcQryExchangeCombActionField();

typedef struct CThostFtdcProductExchRateField CThostFtdcProductExchRateField;
CThostFtdcProductExchRateField* newCThostFtdcProductExchRateField();

typedef struct CThostFtdcQryProductExchRateField CThostFtdcQryProductExchRateField;
CThostFtdcQryProductExchRateField* newCThostFtdcQryProductExchRateField();

typedef struct CThostFtdcQryForQuoteParamField CThostFtdcQryForQuoteParamField;
CThostFtdcQryForQuoteParamField* newCThostFtdcQryForQuoteParamField();

typedef struct CThostFtdcForQuoteParamField CThostFtdcForQuoteParamField;
CThostFtdcForQuoteParamField* newCThostFtdcForQuoteParamField();

typedef struct CThostFtdcMMOptionInstrCommRateField CThostFtdcMMOptionInstrCommRateField;
CThostFtdcMMOptionInstrCommRateField* newCThostFtdcMMOptionInstrCommRateField();

typedef struct CThostFtdcQryMMOptionInstrCommRateField CThostFtdcQryMMOptionInstrCommRateField;
CThostFtdcQryMMOptionInstrCommRateField* newCThostFtdcQryMMOptionInstrCommRateField();

typedef struct CThostFtdcMMInstrumentCommissionRateField CThostFtdcMMInstrumentCommissionRateField;
CThostFtdcMMInstrumentCommissionRateField* newCThostFtdcMMInstrumentCommissionRateField();

typedef struct CThostFtdcQryMMInstrumentCommissionRateField CThostFtdcQryMMInstrumentCommissionRateField;
CThostFtdcQryMMInstrumentCommissionRateField* newCThostFtdcQryMMInstrumentCommissionRateField();

typedef struct CThostFtdcInstrumentOrderCommRateField CThostFtdcInstrumentOrderCommRateField;
CThostFtdcInstrumentOrderCommRateField* newCThostFtdcInstrumentOrderCommRateField();

typedef struct CThostFtdcQryInstrumentOrderCommRateField CThostFtdcQryInstrumentOrderCommRateField;
CThostFtdcQryInstrumentOrderCommRateField* newCThostFtdcQryInstrumentOrderCommRateField();

typedef struct CThostFtdcTradeParamField CThostFtdcTradeParamField;
CThostFtdcTradeParamField* newCThostFtdcTradeParamField();

typedef struct CThostFtdcInstrumentMarginRateULField CThostFtdcInstrumentMarginRateULField;
CThostFtdcInstrumentMarginRateULField* newCThostFtdcInstrumentMarginRateULField();

typedef struct CThostFtdcFutureLimitPosiParamField CThostFtdcFutureLimitPosiParamField;
CThostFtdcFutureLimitPosiParamField* newCThostFtdcFutureLimitPosiParamField();

typedef struct CThostFtdcLoginForbiddenIPField CThostFtdcLoginForbiddenIPField;
CThostFtdcLoginForbiddenIPField* newCThostFtdcLoginForbiddenIPField();

typedef struct CThostFtdcIPListField CThostFtdcIPListField;
CThostFtdcIPListField* newCThostFtdcIPListField();

typedef struct CThostFtdcInputOptionSelfCloseField CThostFtdcInputOptionSelfCloseField;
CThostFtdcInputOptionSelfCloseField* newCThostFtdcInputOptionSelfCloseField();

typedef struct CThostFtdcInputOptionSelfCloseActionField CThostFtdcInputOptionSelfCloseActionField;
CThostFtdcInputOptionSelfCloseActionField* newCThostFtdcInputOptionSelfCloseActionField();

typedef struct CThostFtdcOptionSelfCloseField CThostFtdcOptionSelfCloseField;
CThostFtdcOptionSelfCloseField* newCThostFtdcOptionSelfCloseField();

typedef struct CThostFtdcOptionSelfCloseActionField CThostFtdcOptionSelfCloseActionField;
CThostFtdcOptionSelfCloseActionField* newCThostFtdcOptionSelfCloseActionField();

typedef struct CThostFtdcQryOptionSelfCloseField CThostFtdcQryOptionSelfCloseField;
CThostFtdcQryOptionSelfCloseField* newCThostFtdcQryOptionSelfCloseField();

typedef struct CThostFtdcExchangeOptionSelfCloseField CThostFtdcExchangeOptionSelfCloseField;
CThostFtdcExchangeOptionSelfCloseField* newCThostFtdcExchangeOptionSelfCloseField();

typedef struct CThostFtdcQryOptionSelfCloseActionField CThostFtdcQryOptionSelfCloseActionField;
CThostFtdcQryOptionSelfCloseActionField* newCThostFtdcQryOptionSelfCloseActionField();

typedef struct CThostFtdcExchangeOptionSelfCloseActionField CThostFtdcExchangeOptionSelfCloseActionField;
CThostFtdcExchangeOptionSelfCloseActionField* newCThostFtdcExchangeOptionSelfCloseActionField();

typedef struct CThostFtdcSyncDelaySwapField CThostFtdcSyncDelaySwapField;
CThostFtdcSyncDelaySwapField* newCThostFtdcSyncDelaySwapField();

typedef struct CThostFtdcQrySyncDelaySwapField CThostFtdcQrySyncDelaySwapField;
CThostFtdcQrySyncDelaySwapField* newCThostFtdcQrySyncDelaySwapField();

typedef struct CThostFtdcInvestUnitField CThostFtdcInvestUnitField;
CThostFtdcInvestUnitField* newCThostFtdcInvestUnitField();

typedef struct CThostFtdcQryInvestUnitField CThostFtdcQryInvestUnitField;
CThostFtdcQryInvestUnitField* newCThostFtdcQryInvestUnitField();

typedef struct CThostFtdcSecAgentCheckModeField CThostFtdcSecAgentCheckModeField;
CThostFtdcSecAgentCheckModeField* newCThostFtdcSecAgentCheckModeField();

typedef struct CThostFtdcSecAgentTradeInfoField CThostFtdcSecAgentTradeInfoField;
CThostFtdcSecAgentTradeInfoField* newCThostFtdcSecAgentTradeInfoField();

typedef struct CThostFtdcMarketDataField CThostFtdcMarketDataField;
CThostFtdcMarketDataField* newCThostFtdcMarketDataField();

typedef struct CThostFtdcMarketDataBaseField CThostFtdcMarketDataBaseField;
CThostFtdcMarketDataBaseField* newCThostFtdcMarketDataBaseField();

typedef struct CThostFtdcMarketDataStaticField CThostFtdcMarketDataStaticField;
CThostFtdcMarketDataStaticField* newCThostFtdcMarketDataStaticField();

typedef struct CThostFtdcMarketDataLastMatchField CThostFtdcMarketDataLastMatchField;
CThostFtdcMarketDataLastMatchField* newCThostFtdcMarketDataLastMatchField();

typedef struct CThostFtdcMarketDataBestPriceField CThostFtdcMarketDataBestPriceField;
CThostFtdcMarketDataBestPriceField* newCThostFtdcMarketDataBestPriceField();

typedef struct CThostFtdcMarketDataBid23Field CThostFtdcMarketDataBid23Field;
CThostFtdcMarketDataBid23Field* newCThostFtdcMarketDataBid23Field();

typedef struct CThostFtdcMarketDataAsk23Field CThostFtdcMarketDataAsk23Field;
CThostFtdcMarketDataAsk23Field* newCThostFtdcMarketDataAsk23Field();

typedef struct CThostFtdcMarketDataBid45Field CThostFtdcMarketDataBid45Field;
CThostFtdcMarketDataBid45Field* newCThostFtdcMarketDataBid45Field();

typedef struct CThostFtdcMarketDataAsk45Field CThostFtdcMarketDataAsk45Field;
CThostFtdcMarketDataAsk45Field* newCThostFtdcMarketDataAsk45Field();

typedef struct CThostFtdcMarketDataUpdateTimeField CThostFtdcMarketDataUpdateTimeField;
CThostFtdcMarketDataUpdateTimeField* newCThostFtdcMarketDataUpdateTimeField();

typedef struct CThostFtdcMarketDataExchangeField CThostFtdcMarketDataExchangeField;
CThostFtdcMarketDataExchangeField* newCThostFtdcMarketDataExchangeField();

typedef struct CThostFtdcSpecificInstrumentField CThostFtdcSpecificInstrumentField;
CThostFtdcSpecificInstrumentField* newCThostFtdcSpecificInstrumentField();

typedef struct CThostFtdcInstrumentStatusField CThostFtdcInstrumentStatusField;
CThostFtdcInstrumentStatusField* newCThostFtdcInstrumentStatusField();

typedef struct CThostFtdcQryInstrumentStatusField CThostFtdcQryInstrumentStatusField;
CThostFtdcQryInstrumentStatusField* newCThostFtdcQryInstrumentStatusField();

typedef struct CThostFtdcInvestorAccountField CThostFtdcInvestorAccountField;
CThostFtdcInvestorAccountField* newCThostFtdcInvestorAccountField();

typedef struct CThostFtdcPositionProfitAlgorithmField CThostFtdcPositionProfitAlgorithmField;
CThostFtdcPositionProfitAlgorithmField* newCThostFtdcPositionProfitAlgorithmField();

typedef struct CThostFtdcDiscountField CThostFtdcDiscountField;
CThostFtdcDiscountField* newCThostFtdcDiscountField();

typedef struct CThostFtdcQryTransferBankField CThostFtdcQryTransferBankField;
CThostFtdcQryTransferBankField* newCThostFtdcQryTransferBankField();

typedef struct CThostFtdcTransferBankField CThostFtdcTransferBankField;
CThostFtdcTransferBankField* newCThostFtdcTransferBankField();

typedef struct CThostFtdcQryInvestorPositionDetailField CThostFtdcQryInvestorPositionDetailField;
CThostFtdcQryInvestorPositionDetailField* newCThostFtdcQryInvestorPositionDetailField();

typedef struct CThostFtdcInvestorPositionDetailField CThostFtdcInvestorPositionDetailField;
CThostFtdcInvestorPositionDetailField* newCThostFtdcInvestorPositionDetailField();

typedef struct CThostFtdcTradingAccountPasswordField CThostFtdcTradingAccountPasswordField;
CThostFtdcTradingAccountPasswordField* newCThostFtdcTradingAccountPasswordField();

typedef struct CThostFtdcMDTraderOfferField CThostFtdcMDTraderOfferField;
CThostFtdcMDTraderOfferField* newCThostFtdcMDTraderOfferField();

typedef struct CThostFtdcQryMDTraderOfferField CThostFtdcQryMDTraderOfferField;
CThostFtdcQryMDTraderOfferField* newCThostFtdcQryMDTraderOfferField();

typedef struct CThostFtdcQryNoticeField CThostFtdcQryNoticeField;
CThostFtdcQryNoticeField* newCThostFtdcQryNoticeField();

typedef struct CThostFtdcNoticeField CThostFtdcNoticeField;
CThostFtdcNoticeField* newCThostFtdcNoticeField();

typedef struct CThostFtdcUserRightField CThostFtdcUserRightField;
CThostFtdcUserRightField* newCThostFtdcUserRightField();

typedef struct CThostFtdcQrySettlementInfoConfirmField CThostFtdcQrySettlementInfoConfirmField;
CThostFtdcQrySettlementInfoConfirmField* newCThostFtdcQrySettlementInfoConfirmField();

typedef struct CThostFtdcLoadSettlementInfoField CThostFtdcLoadSettlementInfoField;
CThostFtdcLoadSettlementInfoField* newCThostFtdcLoadSettlementInfoField();

typedef struct CThostFtdcBrokerWithdrawAlgorithmField CThostFtdcBrokerWithdrawAlgorithmField;
CThostFtdcBrokerWithdrawAlgorithmField* newCThostFtdcBrokerWithdrawAlgorithmField();

typedef struct CThostFtdcTradingAccountPasswordUpdateV1Field CThostFtdcTradingAccountPasswordUpdateV1Field;
CThostFtdcTradingAccountPasswordUpdateV1Field* newCThostFtdcTradingAccountPasswordUpdateV1Field();

typedef struct CThostFtdcTradingAccountPasswordUpdateField CThostFtdcTradingAccountPasswordUpdateField;
CThostFtdcTradingAccountPasswordUpdateField* newCThostFtdcTradingAccountPasswordUpdateField();

typedef struct CThostFtdcQryCombinationLegField CThostFtdcQryCombinationLegField;
CThostFtdcQryCombinationLegField* newCThostFtdcQryCombinationLegField();

typedef struct CThostFtdcQrySyncStatusField CThostFtdcQrySyncStatusField;
CThostFtdcQrySyncStatusField* newCThostFtdcQrySyncStatusField();

typedef struct CThostFtdcCombinationLegField CThostFtdcCombinationLegField;
CThostFtdcCombinationLegField* newCThostFtdcCombinationLegField();

typedef struct CThostFtdcSyncStatusField CThostFtdcSyncStatusField;
CThostFtdcSyncStatusField* newCThostFtdcSyncStatusField();

typedef struct CThostFtdcQryLinkManField CThostFtdcQryLinkManField;
CThostFtdcQryLinkManField* newCThostFtdcQryLinkManField();

typedef struct CThostFtdcLinkManField CThostFtdcLinkManField;
CThostFtdcLinkManField* newCThostFtdcLinkManField();

typedef struct CThostFtdcQryBrokerUserEventField CThostFtdcQryBrokerUserEventField;
CThostFtdcQryBrokerUserEventField* newCThostFtdcQryBrokerUserEventField();

typedef struct CThostFtdcBrokerUserEventField CThostFtdcBrokerUserEventField;
CThostFtdcBrokerUserEventField* newCThostFtdcBrokerUserEventField();

typedef struct CThostFtdcQryContractBankField CThostFtdcQryContractBankField;
CThostFtdcQryContractBankField* newCThostFtdcQryContractBankField();

typedef struct CThostFtdcContractBankField CThostFtdcContractBankField;
CThostFtdcContractBankField* newCThostFtdcContractBankField();

typedef struct CThostFtdcInvestorPositionCombineDetailField CThostFtdcInvestorPositionCombineDetailField;
CThostFtdcInvestorPositionCombineDetailField* newCThostFtdcInvestorPositionCombineDetailField();

typedef struct CThostFtdcParkedOrderField CThostFtdcParkedOrderField;
CThostFtdcParkedOrderField* newCThostFtdcParkedOrderField();

typedef struct CThostFtdcParkedOrderActionField CThostFtdcParkedOrderActionField;
CThostFtdcParkedOrderActionField* newCThostFtdcParkedOrderActionField();

typedef struct CThostFtdcQryParkedOrderField CThostFtdcQryParkedOrderField;
CThostFtdcQryParkedOrderField* newCThostFtdcQryParkedOrderField();

typedef struct CThostFtdcQryParkedOrderActionField CThostFtdcQryParkedOrderActionField;
CThostFtdcQryParkedOrderActionField* newCThostFtdcQryParkedOrderActionField();

typedef struct CThostFtdcRemoveParkedOrderField CThostFtdcRemoveParkedOrderField;
CThostFtdcRemoveParkedOrderField* newCThostFtdcRemoveParkedOrderField();

typedef struct CThostFtdcRemoveParkedOrderActionField CThostFtdcRemoveParkedOrderActionField;
CThostFtdcRemoveParkedOrderActionField* newCThostFtdcRemoveParkedOrderActionField();

typedef struct CThostFtdcInvestorWithdrawAlgorithmField CThostFtdcInvestorWithdrawAlgorithmField;
CThostFtdcInvestorWithdrawAlgorithmField* newCThostFtdcInvestorWithdrawAlgorithmField();

typedef struct CThostFtdcQryInvestorPositionCombineDetailField CThostFtdcQryInvestorPositionCombineDetailField;
CThostFtdcQryInvestorPositionCombineDetailField* newCThostFtdcQryInvestorPositionCombineDetailField();

typedef struct CThostFtdcMarketDataAveragePriceField CThostFtdcMarketDataAveragePriceField;
CThostFtdcMarketDataAveragePriceField* newCThostFtdcMarketDataAveragePriceField();

typedef struct CThostFtdcVerifyInvestorPasswordField CThostFtdcVerifyInvestorPasswordField;
CThostFtdcVerifyInvestorPasswordField* newCThostFtdcVerifyInvestorPasswordField();

typedef struct CThostFtdcUserIPField CThostFtdcUserIPField;
CThostFtdcUserIPField* newCThostFtdcUserIPField();

typedef struct CThostFtdcTradingNoticeInfoField CThostFtdcTradingNoticeInfoField;
CThostFtdcTradingNoticeInfoField* newCThostFtdcTradingNoticeInfoField();

typedef struct CThostFtdcTradingNoticeField CThostFtdcTradingNoticeField;
CThostFtdcTradingNoticeField* newCThostFtdcTradingNoticeField();

typedef struct CThostFtdcQryTradingNoticeField CThostFtdcQryTradingNoticeField;
CThostFtdcQryTradingNoticeField* newCThostFtdcQryTradingNoticeField();

typedef struct CThostFtdcQryErrOrderField CThostFtdcQryErrOrderField;
CThostFtdcQryErrOrderField* newCThostFtdcQryErrOrderField();

typedef struct CThostFtdcErrOrderField CThostFtdcErrOrderField;
CThostFtdcErrOrderField* newCThostFtdcErrOrderField();

typedef struct CThostFtdcErrorConditionalOrderField CThostFtdcErrorConditionalOrderField;
CThostFtdcErrorConditionalOrderField* newCThostFtdcErrorConditionalOrderField();

typedef struct CThostFtdcQryErrOrderActionField CThostFtdcQryErrOrderActionField;
CThostFtdcQryErrOrderActionField* newCThostFtdcQryErrOrderActionField();

typedef struct CThostFtdcErrOrderActionField CThostFtdcErrOrderActionField;
CThostFtdcErrOrderActionField* newCThostFtdcErrOrderActionField();

typedef struct CThostFtdcQryExchangeSequenceField CThostFtdcQryExchangeSequenceField;
CThostFtdcQryExchangeSequenceField* newCThostFtdcQryExchangeSequenceField();

typedef struct CThostFtdcExchangeSequenceField CThostFtdcExchangeSequenceField;
CThostFtdcExchangeSequenceField* newCThostFtdcExchangeSequenceField();

typedef struct CThostFtdcQueryMaxOrderVolumeWithPriceField CThostFtdcQueryMaxOrderVolumeWithPriceField;
CThostFtdcQueryMaxOrderVolumeWithPriceField* newCThostFtdcQueryMaxOrderVolumeWithPriceField();

typedef struct CThostFtdcQryBrokerTradingParamsField CThostFtdcQryBrokerTradingParamsField;
CThostFtdcQryBrokerTradingParamsField* newCThostFtdcQryBrokerTradingParamsField();

typedef struct CThostFtdcBrokerTradingParamsField CThostFtdcBrokerTradingParamsField;
CThostFtdcBrokerTradingParamsField* newCThostFtdcBrokerTradingParamsField();

typedef struct CThostFtdcQryBrokerTradingAlgosField CThostFtdcQryBrokerTradingAlgosField;
CThostFtdcQryBrokerTradingAlgosField* newCThostFtdcQryBrokerTradingAlgosField();

typedef struct CThostFtdcBrokerTradingAlgosField CThostFtdcBrokerTradingAlgosField;
CThostFtdcBrokerTradingAlgosField* newCThostFtdcBrokerTradingAlgosField();

typedef struct CThostFtdcQueryBrokerDepositField CThostFtdcQueryBrokerDepositField;
CThostFtdcQueryBrokerDepositField* newCThostFtdcQueryBrokerDepositField();

typedef struct CThostFtdcBrokerDepositField CThostFtdcBrokerDepositField;
CThostFtdcBrokerDepositField* newCThostFtdcBrokerDepositField();

typedef struct CThostFtdcQryCFMMCBrokerKeyField CThostFtdcQryCFMMCBrokerKeyField;
CThostFtdcQryCFMMCBrokerKeyField* newCThostFtdcQryCFMMCBrokerKeyField();

typedef struct CThostFtdcCFMMCBrokerKeyField CThostFtdcCFMMCBrokerKeyField;
CThostFtdcCFMMCBrokerKeyField* newCThostFtdcCFMMCBrokerKeyField();

typedef struct CThostFtdcCFMMCTradingAccountKeyField CThostFtdcCFMMCTradingAccountKeyField;
CThostFtdcCFMMCTradingAccountKeyField* newCThostFtdcCFMMCTradingAccountKeyField();

typedef struct CThostFtdcQryCFMMCTradingAccountKeyField CThostFtdcQryCFMMCTradingAccountKeyField;
CThostFtdcQryCFMMCTradingAccountKeyField* newCThostFtdcQryCFMMCTradingAccountKeyField();

typedef struct CThostFtdcBrokerUserOTPParamField CThostFtdcBrokerUserOTPParamField;
CThostFtdcBrokerUserOTPParamField* newCThostFtdcBrokerUserOTPParamField();

typedef struct CThostFtdcManualSyncBrokerUserOTPField CThostFtdcManualSyncBrokerUserOTPField;
CThostFtdcManualSyncBrokerUserOTPField* newCThostFtdcManualSyncBrokerUserOTPField();

typedef struct CThostFtdcCommRateModelField CThostFtdcCommRateModelField;
CThostFtdcCommRateModelField* newCThostFtdcCommRateModelField();

typedef struct CThostFtdcQryCommRateModelField CThostFtdcQryCommRateModelField;
CThostFtdcQryCommRateModelField* newCThostFtdcQryCommRateModelField();

typedef struct CThostFtdcMarginModelField CThostFtdcMarginModelField;
CThostFtdcMarginModelField* newCThostFtdcMarginModelField();

typedef struct CThostFtdcQryMarginModelField CThostFtdcQryMarginModelField;
CThostFtdcQryMarginModelField* newCThostFtdcQryMarginModelField();

typedef struct CThostFtdcEWarrantOffsetField CThostFtdcEWarrantOffsetField;
CThostFtdcEWarrantOffsetField* newCThostFtdcEWarrantOffsetField();

typedef struct CThostFtdcQryEWarrantOffsetField CThostFtdcQryEWarrantOffsetField;
CThostFtdcQryEWarrantOffsetField* newCThostFtdcQryEWarrantOffsetField();

typedef struct CThostFtdcQryInvestorProductGroupMarginField CThostFtdcQryInvestorProductGroupMarginField;
CThostFtdcQryInvestorProductGroupMarginField* newCThostFtdcQryInvestorProductGroupMarginField();

typedef struct CThostFtdcInvestorProductGroupMarginField CThostFtdcInvestorProductGroupMarginField;
CThostFtdcInvestorProductGroupMarginField* newCThostFtdcInvestorProductGroupMarginField();

typedef struct CThostFtdcQueryCFMMCTradingAccountTokenField CThostFtdcQueryCFMMCTradingAccountTokenField;
CThostFtdcQueryCFMMCTradingAccountTokenField* newCThostFtdcQueryCFMMCTradingAccountTokenField();

typedef struct CThostFtdcCFMMCTradingAccountTokenField CThostFtdcCFMMCTradingAccountTokenField;
CThostFtdcCFMMCTradingAccountTokenField* newCThostFtdcCFMMCTradingAccountTokenField();

typedef struct CThostFtdcQryProductGroupField CThostFtdcQryProductGroupField;
CThostFtdcQryProductGroupField* newCThostFtdcQryProductGroupField();

typedef struct CThostFtdcProductGroupField CThostFtdcProductGroupField;
CThostFtdcProductGroupField* newCThostFtdcProductGroupField();

typedef struct CThostFtdcBulletinField CThostFtdcBulletinField;
CThostFtdcBulletinField* newCThostFtdcBulletinField();

typedef struct CThostFtdcQryBulletinField CThostFtdcQryBulletinField;
CThostFtdcQryBulletinField* newCThostFtdcQryBulletinField();

typedef struct CThostFtdcMulticastInstrumentField CThostFtdcMulticastInstrumentField;
CThostFtdcMulticastInstrumentField* newCThostFtdcMulticastInstrumentField();

typedef struct CThostFtdcQryMulticastInstrumentField CThostFtdcQryMulticastInstrumentField;
CThostFtdcQryMulticastInstrumentField* newCThostFtdcQryMulticastInstrumentField();

typedef struct CThostFtdcAppIDAuthAssignField CThostFtdcAppIDAuthAssignField;
CThostFtdcAppIDAuthAssignField* newCThostFtdcAppIDAuthAssignField();

typedef struct CThostFtdcReqOpenAccountField CThostFtdcReqOpenAccountField;
CThostFtdcReqOpenAccountField* newCThostFtdcReqOpenAccountField();

typedef struct CThostFtdcReqCancelAccountField CThostFtdcReqCancelAccountField;
CThostFtdcReqCancelAccountField* newCThostFtdcReqCancelAccountField();

typedef struct CThostFtdcReqChangeAccountField CThostFtdcReqChangeAccountField;
CThostFtdcReqChangeAccountField* newCThostFtdcReqChangeAccountField();

typedef struct CThostFtdcReqTransferField CThostFtdcReqTransferField;
CThostFtdcReqTransferField* newCThostFtdcReqTransferField();

typedef struct CThostFtdcRspTransferField CThostFtdcRspTransferField;
CThostFtdcRspTransferField* newCThostFtdcRspTransferField();

typedef struct CThostFtdcReqRepealField CThostFtdcReqRepealField;
CThostFtdcReqRepealField* newCThostFtdcReqRepealField();

typedef struct CThostFtdcRspRepealField CThostFtdcRspRepealField;
CThostFtdcRspRepealField* newCThostFtdcRspRepealField();

typedef struct CThostFtdcReqQueryAccountField CThostFtdcReqQueryAccountField;
CThostFtdcReqQueryAccountField* newCThostFtdcReqQueryAccountField();

typedef struct CThostFtdcRspQueryAccountField CThostFtdcRspQueryAccountField;
CThostFtdcRspQueryAccountField* newCThostFtdcRspQueryAccountField();

typedef struct CThostFtdcFutureSignIOField CThostFtdcFutureSignIOField;
CThostFtdcFutureSignIOField* newCThostFtdcFutureSignIOField();

typedef struct CThostFtdcRspFutureSignInField CThostFtdcRspFutureSignInField;
CThostFtdcRspFutureSignInField* newCThostFtdcRspFutureSignInField();

typedef struct CThostFtdcReqFutureSignOutField CThostFtdcReqFutureSignOutField;
CThostFtdcReqFutureSignOutField* newCThostFtdcReqFutureSignOutField();

typedef struct CThostFtdcRspFutureSignOutField CThostFtdcRspFutureSignOutField;
CThostFtdcRspFutureSignOutField* newCThostFtdcRspFutureSignOutField();

typedef struct CThostFtdcReqQueryTradeResultBySerialField CThostFtdcReqQueryTradeResultBySerialField;
CThostFtdcReqQueryTradeResultBySerialField* newCThostFtdcReqQueryTradeResultBySerialField();

typedef struct CThostFtdcRspQueryTradeResultBySerialField CThostFtdcRspQueryTradeResultBySerialField;
CThostFtdcRspQueryTradeResultBySerialField* newCThostFtdcRspQueryTradeResultBySerialField();

typedef struct CThostFtdcReqDayEndFileReadyField CThostFtdcReqDayEndFileReadyField;
CThostFtdcReqDayEndFileReadyField* newCThostFtdcReqDayEndFileReadyField();

typedef struct CThostFtdcReturnResultField CThostFtdcReturnResultField;
CThostFtdcReturnResultField* newCThostFtdcReturnResultField();

typedef struct CThostFtdcVerifyFuturePasswordField CThostFtdcVerifyFuturePasswordField;
CThostFtdcVerifyFuturePasswordField* newCThostFtdcVerifyFuturePasswordField();

typedef struct CThostFtdcVerifyCustInfoField CThostFtdcVerifyCustInfoField;
CThostFtdcVerifyCustInfoField* newCThostFtdcVerifyCustInfoField();

typedef struct CThostFtdcVerifyFuturePasswordAndCustInfoField CThostFtdcVerifyFuturePasswordAndCustInfoField;
CThostFtdcVerifyFuturePasswordAndCustInfoField* newCThostFtdcVerifyFuturePasswordAndCustInfoField();

typedef struct CThostFtdcDepositResultInformField CThostFtdcDepositResultInformField;
CThostFtdcDepositResultInformField* newCThostFtdcDepositResultInformField();

typedef struct CThostFtdcReqSyncKeyField CThostFtdcReqSyncKeyField;
CThostFtdcReqSyncKeyField* newCThostFtdcReqSyncKeyField();

typedef struct CThostFtdcRspSyncKeyField CThostFtdcRspSyncKeyField;
CThostFtdcRspSyncKeyField* newCThostFtdcRspSyncKeyField();

typedef struct CThostFtdcNotifyQueryAccountField CThostFtdcNotifyQueryAccountField;
CThostFtdcNotifyQueryAccountField* newCThostFtdcNotifyQueryAccountField();

typedef struct CThostFtdcTransferSerialField CThostFtdcTransferSerialField;
CThostFtdcTransferSerialField* newCThostFtdcTransferSerialField();

typedef struct CThostFtdcQryTransferSerialField CThostFtdcQryTransferSerialField;
CThostFtdcQryTransferSerialField* newCThostFtdcQryTransferSerialField();

typedef struct CThostFtdcNotifyFutureSignInField CThostFtdcNotifyFutureSignInField;
CThostFtdcNotifyFutureSignInField* newCThostFtdcNotifyFutureSignInField();

typedef struct CThostFtdcNotifyFutureSignOutField CThostFtdcNotifyFutureSignOutField;
CThostFtdcNotifyFutureSignOutField* newCThostFtdcNotifyFutureSignOutField();

typedef struct CThostFtdcNotifySyncKeyField CThostFtdcNotifySyncKeyField;
CThostFtdcNotifySyncKeyField* newCThostFtdcNotifySyncKeyField();

typedef struct CThostFtdcQryAccountregisterField CThostFtdcQryAccountregisterField;
CThostFtdcQryAccountregisterField* newCThostFtdcQryAccountregisterField();

typedef struct CThostFtdcAccountregisterField CThostFtdcAccountregisterField;
CThostFtdcAccountregisterField* newCThostFtdcAccountregisterField();

typedef struct CThostFtdcOpenAccountField CThostFtdcOpenAccountField;
CThostFtdcOpenAccountField* newCThostFtdcOpenAccountField();

typedef struct CThostFtdcCancelAccountField CThostFtdcCancelAccountField;
CThostFtdcCancelAccountField* newCThostFtdcCancelAccountField();

typedef struct CThostFtdcChangeAccountField CThostFtdcChangeAccountField;
CThostFtdcChangeAccountField* newCThostFtdcChangeAccountField();

typedef struct CThostFtdcSecAgentACIDMapField CThostFtdcSecAgentACIDMapField;
CThostFtdcSecAgentACIDMapField* newCThostFtdcSecAgentACIDMapField();

typedef struct CThostFtdcQrySecAgentACIDMapField CThostFtdcQrySecAgentACIDMapField;
CThostFtdcQrySecAgentACIDMapField* newCThostFtdcQrySecAgentACIDMapField();

typedef struct CThostFtdcUserRightsAssignField CThostFtdcUserRightsAssignField;
CThostFtdcUserRightsAssignField* newCThostFtdcUserRightsAssignField();

typedef struct CThostFtdcBrokerUserRightAssignField CThostFtdcBrokerUserRightAssignField;
CThostFtdcBrokerUserRightAssignField* newCThostFtdcBrokerUserRightAssignField();

typedef struct CThostFtdcDRTransferField CThostFtdcDRTransferField;
CThostFtdcDRTransferField* newCThostFtdcDRTransferField();

typedef struct CThostFtdcFensUserInfoField CThostFtdcFensUserInfoField;
CThostFtdcFensUserInfoField* newCThostFtdcFensUserInfoField();

typedef struct CThostFtdcCurrTransferIdentityField CThostFtdcCurrTransferIdentityField;
CThostFtdcCurrTransferIdentityField* newCThostFtdcCurrTransferIdentityField();

typedef struct CThostFtdcLoginForbiddenUserField CThostFtdcLoginForbiddenUserField;
CThostFtdcLoginForbiddenUserField* newCThostFtdcLoginForbiddenUserField();

typedef struct CThostFtdcQryLoginForbiddenUserField CThostFtdcQryLoginForbiddenUserField;
CThostFtdcQryLoginForbiddenUserField* newCThostFtdcQryLoginForbiddenUserField();

typedef struct CThostFtdcMulticastGroupInfoField CThostFtdcMulticastGroupInfoField;
CThostFtdcMulticastGroupInfoField* newCThostFtdcMulticastGroupInfoField();

typedef struct CThostFtdcTradingAccountReserveField CThostFtdcTradingAccountReserveField;
CThostFtdcTradingAccountReserveField* newCThostFtdcTradingAccountReserveField();

typedef struct CThostFtdcQryLoginForbiddenIPField CThostFtdcQryLoginForbiddenIPField;
CThostFtdcQryLoginForbiddenIPField* newCThostFtdcQryLoginForbiddenIPField();

typedef struct CThostFtdcQryIPListField CThostFtdcQryIPListField;
CThostFtdcQryIPListField* newCThostFtdcQryIPListField();

typedef struct CThostFtdcQryUserRightsAssignField CThostFtdcQryUserRightsAssignField;
CThostFtdcQryUserRightsAssignField* newCThostFtdcQryUserRightsAssignField();

typedef struct CThostFtdcReserveOpenAccountConfirmField CThostFtdcReserveOpenAccountConfirmField;
CThostFtdcReserveOpenAccountConfirmField* newCThostFtdcReserveOpenAccountConfirmField();

typedef struct CThostFtdcReserveOpenAccountField CThostFtdcReserveOpenAccountField;
CThostFtdcReserveOpenAccountField* newCThostFtdcReserveOpenAccountField();

typedef struct CThostFtdcAccountPropertyField CThostFtdcAccountPropertyField;
CThostFtdcAccountPropertyField* newCThostFtdcAccountPropertyField();

typedef struct CThostFtdcQryCurrDRIdentityField CThostFtdcQryCurrDRIdentityField;
CThostFtdcQryCurrDRIdentityField* newCThostFtdcQryCurrDRIdentityField();

typedef struct CThostFtdcCurrDRIdentityField CThostFtdcCurrDRIdentityField;
CThostFtdcCurrDRIdentityField* newCThostFtdcCurrDRIdentityField();

typedef struct CThostFtdcQrySecAgentCheckModeField CThostFtdcQrySecAgentCheckModeField;
CThostFtdcQrySecAgentCheckModeField* newCThostFtdcQrySecAgentCheckModeField();

typedef struct CThostFtdcQrySecAgentTradeInfoField CThostFtdcQrySecAgentTradeInfoField;
CThostFtdcQrySecAgentTradeInfoField* newCThostFtdcQrySecAgentTradeInfoField();

typedef struct CThostFtdcUserSystemInfoField CThostFtdcUserSystemInfoField;
CThostFtdcUserSystemInfoField* newCThostFtdcUserSystemInfoField();

typedef struct CThostFtdcReqUserAuthMethodField CThostFtdcReqUserAuthMethodField;
CThostFtdcReqUserAuthMethodField* newCThostFtdcReqUserAuthMethodField();

typedef struct CThostFtdcRspUserAuthMethodField CThostFtdcRspUserAuthMethodField;
CThostFtdcRspUserAuthMethodField* newCThostFtdcRspUserAuthMethodField();

typedef struct CThostFtdcReqGenUserCaptchaField CThostFtdcReqGenUserCaptchaField;
CThostFtdcReqGenUserCaptchaField* newCThostFtdcReqGenUserCaptchaField();

typedef struct CThostFtdcRspGenUserCaptchaField CThostFtdcRspGenUserCaptchaField;
CThostFtdcRspGenUserCaptchaField* newCThostFtdcRspGenUserCaptchaField();

typedef struct CThostFtdcReqGenUserTextField CThostFtdcReqGenUserTextField;
CThostFtdcReqGenUserTextField* newCThostFtdcReqGenUserTextField();

typedef struct CThostFtdcRspGenUserTextField CThostFtdcRspGenUserTextField;
CThostFtdcRspGenUserTextField* newCThostFtdcRspGenUserTextField();

typedef struct CThostFtdcReqUserLoginWithCaptchaField CThostFtdcReqUserLoginWithCaptchaField;
CThostFtdcReqUserLoginWithCaptchaField* newCThostFtdcReqUserLoginWithCaptchaField();

typedef struct CThostFtdcReqUserLoginWithTextField CThostFtdcReqUserLoginWithTextField;
CThostFtdcReqUserLoginWithTextField* newCThostFtdcReqUserLoginWithTextField();

typedef struct CThostFtdcReqUserLoginWithOTPField CThostFtdcReqUserLoginWithOTPField;
CThostFtdcReqUserLoginWithOTPField* newCThostFtdcReqUserLoginWithOTPField();

typedef struct CThostFtdcReqApiHandshakeField CThostFtdcReqApiHandshakeField;
CThostFtdcReqApiHandshakeField* newCThostFtdcReqApiHandshakeField();

typedef struct CThostFtdcRspApiHandshakeField CThostFtdcRspApiHandshakeField;
CThostFtdcRspApiHandshakeField* newCThostFtdcRspApiHandshakeField();

typedef struct CThostFtdcReqVerifyApiKeyField CThostFtdcReqVerifyApiKeyField;
CThostFtdcReqVerifyApiKeyField* newCThostFtdcReqVerifyApiKeyField();

typedef struct CThostFtdcDepartmentUserField CThostFtdcDepartmentUserField;
CThostFtdcDepartmentUserField* newCThostFtdcDepartmentUserField();

typedef struct CThostFtdcQueryFreqField CThostFtdcQueryFreqField;
CThostFtdcQueryFreqField* newCThostFtdcQueryFreqField();

typedef struct CThostFtdcAuthForbiddenIPField CThostFtdcAuthForbiddenIPField;
CThostFtdcAuthForbiddenIPField* newCThostFtdcAuthForbiddenIPField();

typedef struct CThostFtdcQryAuthForbiddenIPField CThostFtdcQryAuthForbiddenIPField;
CThostFtdcQryAuthForbiddenIPField* newCThostFtdcQryAuthForbiddenIPField();

typedef struct CThostFtdcSyncDelaySwapFrozenField CThostFtdcSyncDelaySwapFrozenField;
CThostFtdcSyncDelaySwapFrozenField* newCThostFtdcSyncDelaySwapFrozenField();

#endif /* _CTP_TYPES_GEN_H */
